[service]
name = "org_entity_search_api_v2"
import_path = "services.active.org_entity_search_api_v2.router"
prefix = "/api"
tag = "org_entity_search_api_v2"
origin = "service"
auth = "public"
needs_data_layer = true