#!/usr/bin/env python3
"""
diagnose_mcp_definition_history_population_gap.py

Diagnostic module that investigates why the `mcp_definition_history` table
remains empty even though the populator and monitor daemons are running.

The diagnostic performs four independent checks by issuing SQL queries
through the *write_service* HTTP API:

1. Counts recent submissions that should have triggered history population.
2. Looks for error entries in the audit log generated by the populator daemon.
3. Retrieves the health status of the populator daemon.
4. Verifies whether any rows actually exist in `mcp_definition_history`.

All queries are sent with parameterised SQL (``params``) and the results
are returned as a dictionary.
"""

from __future__ import annotations

import json
import os
import sys
import time
from datetime import datetime, timedelta
from typing import Any, Dict, List

import requests

# --------------------------------------------------------------------------- #
# Configuration
# --------------------------------------------------------------------------- #
# The write‑service endpoint is expected to accept a JSON payload:
#   {"sql": "<SQL statement>", "params": {...}}
# and return a JSON response with a top‑level ``rows`` key containing a list
# of row dictionaries.
WRITE_SERVICE_URL = os.getenv(
    "WRITE_SERVICE_URL", "http://localhost:8000/query"
).rstrip("/")

# Timeout for HTTP calls (seconds)
HTTP_TIMEOUT = 10


# --------------------------------------------------------------------------- #
# Helper – generic query executor
# --------------------------------------------------------------------------- #
def _run_query(sql: str, params: Dict[str, Any] | None = None) -> List[Dict[str, Any]]:
    """
    Execute a parameterised SQL query via the write‑service.

    Args:
        sql:   The SQL statement with ``:named`` placeholders.
        params: Mapping of placeholder names to values (or ``None``).

    Returns:
        List of rows (each row is a ``dict``).

    Raises:
        RuntimeError: If the HTTP request fails or the service returns an error.
    """
    payload = {"sql": sql, "params": params or {}}
    try:
        resp = requests.post(
            WRITE_SERVICE_URL,
            json=payload,
            timeout=HTTP_TIMEOUT,
        )
        resp.raise_for_status()
    except Exception as exc:
        raise RuntimeError(f"Failed to query write_service: {exc}") from exc

    try:
        data = resp.json()
    except Exception as exc:
        raise RuntimeError(f"Write service returned non‑JSON: {exc}") from exc

    if "error" in data:
        raise RuntimeError(f"Write service error: {data['error']}")

    rows = data.get("rows")
    if rows is None:
        raise RuntimeError("Write service response missing 'rows' field")
    return rows


# --------------------------------------------------------------------------- #
# Diagnostic implementation
# --------------------------------------------------------------------------- #
def diagnose_population_gap() -> Dict[str, Any]:
    """
    Run the full diagnostic and return a structured report.

    The report contains:
        * recent_submission_count – int
        * history_row_count – int
        * populator_daemon – dict with ``status`` and ``last_heartbeat``
        * populator_errors – list of recent error log entries (max 10)
        * notes – free‑form observations / suggestions
    """
    report: Dict[str, Any] = {
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "recent_submission_count": None,
        "history_row_count": None,
        "populator_daemon": {},
        "populator_errors": [],
        "notes": [],
    }

    # ------------------------------------------------------------------- #
    # 1. Recent submissions (last 24 h)
    # ------------------------------------------------------------------- #
    try:
        sql = """
            SELECT COUNT(*) AS cnt
            FROM mcp_submissions
            WHERE submission_time >= :cutoff
        """
        cutoff = (datetime.utcnow() - timedelta(days=1)).isoformat()
        rows = _run_query(sql, {"cutoff": cutoff})
        report["recent_submission_count"] = rows[0]["cnt"]
    except Exception as exc:
        report["notes"].append(f"Failed to count recent submissions: {exc}")

    # ------------------------------------------------------------------- #
    # 2. Existing rows in the history table
    # ------------------------------------------------------------------- #
    try:
        sql = "SELECT COUNT(*) AS cnt FROM mcp_definition_history"
        rows = _run_query(sql)
        report["history_row_count"] = rows[0]["cnt"]
    except Exception as exc:
        report["notes"].append(f"Failed to count history rows: {exc}")

    # ------------------------------------------------------------------- #
    # 3. Populator daemon health
    # ------------------------------------------------------------------- #
    try:
        sql = """
            SELECT status, last_heartbeat
            FROM service_health
            WHERE service_name = :svc
        """
        rows = _run_query(sql, {"svc": "mcp_definition_history_populator_daemon"})
        if rows:
            report["populator_daemon"] = {
                "status": rows[0]["status"],
                "last_heartbeat": rows[0]["last_heartbeat"],
            }
        else:
            report["populator_daemon"] = {"status": "UNKNOWN", "last_heartbeat": None}
            report["notes"].append(
                "No health record found for mcp_definition_history_populator_daemon"
            )
    except Exception as exc:
        report["notes"].append(f"Failed to query service health: {exc}")

    # ------------------------------------------------------------------- #
    # 4. Recent error entries from the populator daemon
    # ------------------------------------------------------------------- #
    try:
        sql = """
            SELECT timestamp, message
            FROM audit_log
            WHERE source = :src
              AND level = 'ERROR'
            ORDER BY timestamp DESC
            LIMIT 10
        """
        rows = _run_query(sql, {"src": "mcp_definition_history_populator_daemon"})
        report["populator_errors"] = [
            {"timestamp": r["timestamp"], "message": r["message"]} for r in rows
        ]
    except Exception as exc:
        report["notes"].append(f"Failed to fetch populator error logs: {exc}")

    # ------------------------------------------------------------------- #
    # 5. Simple heuristic notes
    # ------------------------------------------------------------------- #
    if (
        isinstance(report["recent_submission_count"], int)
        and report["recent_submission_count"] > 0
    ):
        if report["history_row_count"] == 0:
            report["notes"].append(
                "Submissions exist but history table is empty – possible "
                "population failure."
            )
        else:
            report["notes"].append(
                "History table contains rows; population appears to be working."
            )
    else:
        report["notes"].append("No recent submissions found – nothing to populate.")

    if report["populator_daemon"].get("status") != "RUNNING":
        report["notes"].append(
            "Populator daemon is not reported as RUNNING – check daemon logs."
        )

    return report


# --------------------------------------------------------------------------- #
# Command‑line entry point
# --------------------------------------------------------------------------- #
if __name__ == "__main__":
    try:
        result = diagnose_population_gap()
    except Exception as exc:
        print(f"Diagnostic failed: {exc}", file=sys.stderr)
        sys.exit(1)

    # Pretty‑print the JSON result
    print(json.dumps(result, indent=2, sort_keys=True))

    # Basic sanity check – the function must return a dict with the expected keys
    expected_keys = {
        "timestamp",
        "recent_submission_count",
        "history_row_count",
        "populator_daemon",
        "populator_errors",
        "notes",
    }
    missing = expected_keys - result.keys()
    assert not missing, f"Diagnostic result missing keys: {missing}"

    # The diagnostic should always complete without raising – the assert above
    # guarantees that we have a well‑formed payload.