import os

SERVICE_NAME = "gateway_rebuild_all_sh"
SCRIPT_PATH = "/home/workspace/build_start_all_sh"

# Shell script content to write
SHELL_SCRIPT_CONTENT = """#!/bin/bash
# build_start_all_sh - Gateway daemon launcher (supervisord order)
# Generated by gateway_rebuild_all_sh

set -e

# Source environment
if [ -f /home/workspace/env_default.sh ]; then
    source /home/workspace/env_default.sh
fi

# Set PYTHONPATH
export PYTHONPATH=/home/workspace:$PYTHONPATH

# Daemon launch order matches supervisord.conf groups
DAEMONS=(
    "mcp_scanner:/home/workspace/zo_sentinel/mcp_scanner.py"
    "signal_collector:/home/workspace/zo_sentinel/signal_collector.py"
)

for entry in "${DAEMONS[@]}"; do
    IFS=':' read -r name path <<< "$entry"
    echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] Launching $name"
    nohup python3 "$path" >> /home/workspace/logs/"$name".log 2>&1 &
done

echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] All daemons launched"
"""

def main():
    os.makedirs(os.path.dirname(SCRIPT_PATH), exist_ok=True)
    with open(SCRIPT_PATH, 'w') as f:
        f.write(SHELL_SCRIPT_CONTENT)
    os.chmod(SCRIPT_PATH, 0o755)
    print(f"Rebuilt {SCRIPT_PATH}")
    print(f"Lines: {len(SHELL_SCRIPT_CONTENT.splitlines())}")

if __name__ == "__main__":
    main()