import logging
import os

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(name)s] %(levelname)s: %(message)s',
    handlers=[
        logging.FileHandler('/home/workspace/logs/pi_components_supervisord_addition.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

SERVICE_NAME = 'pi_components_supervisord_addition'
OUTPUT_PATH = '/home/workspace/zo_sentinel/supervisord_sentinel_pi_components.conf'

PI_COMPONENTS = [
    {
        'name': 'pi_corpus_ingest',
        'filename': 'pi_corpus_ingest.py',
        'logfile': 'pi_corpus_ingest.log'
    },
    {
        'name': 'pi_quarantine_reviewer',
        'filename': 'pi_quarantine_reviewer.py',
        'logfile': 'pi_quarantine_reviewer.log'
    },
    {
        'name': 'pi_quarantine_promoter',
        'filename': 'pi_quarantine_promoter.py',
        'logfile': 'pi_quarantine_promoter.log'
    },
    {
        'name': 'pi_flagged_review_api',
        'filename': 'pi_flagged_review_api.py',
        'logfile': 'pi_flagged_review_api.log'
    },
    {
        'name': 'pi_harness_runner',
        'filename': 'pi_harness_runner.py',
        'logfile': 'pi_harness_runner.log'
    },
    {
        'name': 'pi_scorer',
        'filename': 'pi_scorer.py',
        'logfile': 'pi_scorer.log'
    }
]

def generate_supervisord_fragment():
    lines = [
        '; ============================================================',
        '; ZO-SENTINEL Phase 8 Pi Components - Supervisord Configuration',
        '; Auto-generated by pi_components_supervisord_addition.py',
        '; ============================================================',
        '',
    ]
    
    for component in PI_COMPONENTS:
        lines.extend([
            f"[program:{component['name']}]",
            f"command=python3 /home/workspace/zo_sentinel/{component['filename']}",
            f"directory=/home/workspace/zo_sentinel",
            f"autostart=true",
            f"autorestart=true",
            f"redirect_stderr=true",
            f"stdout_logfile=/home/workspace/logs/{component['logfile']}",
            f"stdout_logfile_maxbytes=50MB",
            f"stdout_logfile_backups=10",
            f"environment=PYTHONPATH=\"/home/workspace/zo_sentinel\"",
            f"user=ubuntu",
            f"priority=500",
            '',
        ])
    
    return '\n'.join(lines)


def main():
    logger.info(f"Generating supervisord config fragment for {len(PI_COMPONENTS)} Pi components")
    
    fragment = generate_supervisord_fragment()
    
    with open(OUTPUT_PATH, 'w') as f:
        f.write(fragment)
    
    logger.info(f"Supervisord config fragment written to: {OUTPUT_PATH}")
    print(fragment)
    print(f"\n; Add to /home/workspace/zo_sentinel/supervisord_sentinel_full.conf with:")
    print(f";   [include]")
    print(f";   files = /home/workspace/zo_sentinel/supervisord_sentinel_full.conf /home/workspace/zo_sentinel/supervisord_sentinel_pi_components.conf")
    print(f"; Or append this content to supervisord_sentinel_full.conf directly.")
    
    sys.exit(0)


if __name__ == '__main__':
    import sys
    main()