"""The committed schema-truth artifact must still describe the live `app/` source.

WHY (daily-chairman-review, 2026-08-09). 250 builder self-tests went RED in one day; the
largest NAMED class -- 55 of them -- is "imports a name that does not exist". The builder
was never handed the real symbol table, so it invented one. docs/SCHEMA_TRUTH.md is that
table, generated by tools/emit_schema_truth.py and quoted by the DATA ACCESS paragraph
that goes into every build directive.

A generated doc nobody re-generates is worse than no doc: it teaches a WRONG symbol table
with the authority of a checked-in file. This test is the only thing standing between
"generated once" and "quietly wrong". It is in the evaluator.yml pytest allowlist, so CI
actually collects it.

The emitter is run as a SUBPROCESS, never imported: a probe that inlines its subject
freezes its verdict, and importing an emitter would run its writer inside a read-only
test. Stdlib only -- no sqlalchemy, no DATABASE_URL.
"""
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EMITTER = ROOT / "tools" / "emit_schema_truth.py"
MD = ROOT / "docs" / "SCHEMA_TRUTH.md"
JSON_ = ROOT / "docs" / "schema_truth.json"


def _emit(*args):
    return subprocess.run([sys.executable, str(EMITTER), *args],
                          cwd=str(ROOT), capture_output=True, text=True)


def test_emitter_and_artifacts_are_present():
    missing = [str(p.relative_to(ROOT)) for p in (EMITTER, MD, JSON_) if not p.is_file()]
    assert not missing, "schema-truth files missing: " + ", ".join(missing)


def test_committed_artifact_matches_current_source():
    """The load-bearing assertion: regenerate from app/models.py + app/db.py and require
    the committed bytes to match. Goes RED the moment either source changes without the
    artifact being regenerated."""
    r = _emit("--check")
    assert r.returncode == 0, (
        "docs/SCHEMA_TRUTH.md is stale -- run `python tools/emit_schema_truth.py` "
        "and commit the result.\nstdout:\n" + r.stdout + "\nstderr:\n" + r.stderr)
    assert "OK:" in r.stdout, r.stdout


def test_check_mode_writes_nothing():
    before = (MD.read_bytes(), JSON_.read_bytes())
    _emit("--check")
    assert (MD.read_bytes(), JSON_.read_bytes()) == before


def test_artifact_carries_the_real_data_access_seam():
    """Positive facts the DATA ACCESS paragraph asserts to every build. If any of these
    stops being true the paragraph is lying, whatever the doc says."""
    data = json.loads(JSON_.read_text(encoding="utf-8"))
    db_names = set(data["app_db"]["public_names"])
    assert "get_session" in db_names
    assert "Base" in db_names and "SessionLocal" in db_names
    classes = data["app_models"]["classes"]
    assert len(classes) == data["app_models"]["count"] > 0
    assert len(set(classes)) == len(classes), "duplicate class names in the table"


def test_does_not_exist_rows_are_actually_absent():
    """Every symbol the doc calls non-existent must genuinely not be in the table it was
    checked against -- otherwise the doc invents an absence, which is the same defect it
    was built to fix, inverted."""
    data = json.loads(JSON_.read_text(encoding="utf-8"))
    classes = set(data["app_models"]["classes"])
    db_names = set(data["app_db"]["public_names"])
    for row in data["does_not_exist"]:
        w = row["written"]
        for name in ("MCPAxisScores", "VulnAdvisories"):
            if name in w:
                assert name not in classes, f"doc claims {name} is absent, but it exists"
        if "StaticPool" in w:
            assert "StaticPool" not in db_names
    assert data["does_not_exist"] or data["resolved_since"], "no invention rows at all"