# AUTO-GENERATED by tools/generate_spine.py from services/active/ -- DO NOT EDIT.
# Regenerate:  python tools/generate_spine.py --emit .
#
# This is the Option-B build-time spine (SOA design 2026-07-21; CofC 2026-07-23).
# It REPLACES app/main.py's old hand-maintained _OPTIONAL_ROUTERS list and its
# silent `except Exception: pass` mount loop -- the invisibility bug the
# reachability postmortem (FU-044) exists to kill.
#
# CI keeps this file honest:  generate_spine.py --check  (in sync with active/)
#                             generate_spine.py --strict (every active service valid)
# Each import_path below is a LITERAL so the reachability census still counts a
# live service as "mounted" (\bword\b match under app/), not an orphan.
#
# FAIL LOUD:  prod boots anyway but records failures on app.state + /spine/health;
#             a module that declares no router is a VISIBLE skip, not a swallow.
from __future__ import annotations

import importlib
import logging

_log = logging.getLogger("spine")

SPINE_MOUNTS = [   {'name': 'ask_answer_api', 'import_path': 'ask_answer_api', 'prefix': '/api', 'origin': 'live'},
    {   'name': 'ask_corpus_indexer',
        'import_path': 'ask_corpus_indexer',
        'prefix': '/api',
        'origin': 'live'},
    {   'name': 'cadence_admin_api',
        'import_path': 'cadence_admin_api',
        'prefix': '/api/admin/cadence',
        'origin': 'live'},
    {   'name': 'cadence_job_sla_report',
        'import_path': 'services.active.cadence_job_sla_report.router',
        'prefix': '/api',
        'origin': 'service'},
    {   'name': 'config_scan_api',
        'import_path': 'config_scan_api',
        'prefix': '/api',
        'origin': 'live'},
    {   'name': 'dashboard_summary_api',
        'import_path': 'dashboard_summary_api',
        'prefix': '/api',
        'origin': 'live'},
    {   'name': 'entity_report_exporter',
        'import_path': 'entity_report_exporter',
        'prefix': '',
        'origin': 'live'},
    {   'name': 'facet_enum_service',
        'import_path': 'facet_enum_service',
        'prefix': '/api',
        'origin': 'live'},
    {   'name': 'freshness_metadata_api',
        'import_path': 'freshness_metadata_api',
        'prefix': '/api',
        'origin': 'live'},
    {   'name': 'freshness_policy_api',
        'import_path': 'freshness_policy_api',
        'prefix': '',
        'origin': 'live'},
    {   'name': 'media_assets',
        'import_path': 'app.routers.media_assets',
        'prefix': '',
        'origin': 'live'},
    {   'name': 'org_api_key_manager',
        'import_path': 'org_api_key_manager',
        'prefix': '',
        'origin': 'live'},
    {   'name': 'org_entity_search_api',
        'import_path': 'org_entity_search_api',
        'prefix': '/search',
        'origin': 'live'},
    {   'name': 'otx_threat_refs',
        'import_path': 'otx_threat_refs',
        'prefix': '/api',
        'origin': 'live'},
    {   'name': 'overview_dashboard_api',
        'import_path': 'overview_dashboard_api',
        'prefix': '',
        'origin': 'live'},
    {   'name': 'perspective_admin_api',
        'import_path': 'perspective_admin_api',
        'prefix': '/api',
        'origin': 'live'},
    {   'name': 'perspective_diff_service',
        'import_path': 'perspective_diff_service',
        'prefix': '/api',
        'origin': 'live'},
    {   'name': 'perspective_query_api',
        'import_path': 'perspective_query_api',
        'prefix': '/api',
        'origin': 'live'},
    {   'name': 'runtime_deploy_info_endpoint',
        'import_path': 'runtime_deploy_info_endpoint',
        'prefix': '',
        'origin': 'live'},
    {   'name': 'score_dispute_api',
        'import_path': 'score_dispute_api',
        'prefix': '/api',
        'origin': 'live'},
    {   'name': 'scoring_freshness_surface',
        'import_path': 'scoring_freshness_surface',
        'prefix': '',
        'origin': 'live'},
    {   'name': 'server_axis_scores_summary_router',
        'import_path': 'server_axis_scores_summary_router',
        'prefix': '',
        'origin': 'live'},
    {   'name': 'server_compare_api',
        'import_path': 'server_compare_api',
        'prefix': '/api',
        'origin': 'live'},
    {   'name': 'threat_intel_summary_api',
        'import_path': 'threat_intel_summary_api',
        'prefix': '/servers',
        'origin': 'live'},
    {   'name': 'verdict_breakdown_api',
        'import_path': 'verdict_breakdown_api',
        'prefix': '/api',
        'origin': 'live'},
    {   'name': 'verdict_watchlist_service',
        'import_path': 'verdict_watchlist_service',
        'prefix': '',
        'origin': 'live'},
    {   'name': 'vuln_coverage_sla_api',
        'import_path': 'vuln_coverage_sla_api',
        'prefix': '/api',
        'origin': 'live'},
    {   'name': 'vuln_exposure_api',
        'import_path': 'vuln_exposure_api',
        'prefix': '/api',
        'origin': 'live'},
    {   'name': 'vuln_facet_extension',
        'import_path': 'vuln_facet_extension',
        'prefix': '/api',
        'origin': 'live'},
    {   'name': 'vuln_osv_ingestor',
        'import_path': 'vuln_osv_ingestor',
        'prefix': '/api',
        'origin': 'live'},
    {   'name': 'vuln_pkg_enricher',
        'import_path': 'vuln_pkg_enricher',
        'prefix': '/api',
        'origin': 'live'},
    {   'name': 'vuln_registry_linker',
        'import_path': 'vuln_registry_linker',
        'prefix': '/api',
        'origin': 'live'}]


def include_spine(app, strict=False):
    """Mount every active service. Fail LOUD, never SILENT.

    Reproduces the old loop's resilience (a router-less or unimportable module
    never blocks boot) but makes every outcome VISIBLE:

        app.state.spine_mounted            -> [service names actually mounted]
        app.state.spine_skipped_no_router  -> [declared in active/, exposes no router]
        app.state.spine_mount_failures     -> [{service, import_path, error}]  (import/include)

    prod (strict=False): boot anyway; record the three buckets; log failures.
    CI  (strict=True):   raise on the first import/include failure.
    """
    mounted, skipped, failures = [], [], []
    for entry in SPINE_MOUNTS:
        name = entry["name"]
        try:
            mod = importlib.import_module(entry["import_path"])
        except Exception as exc:  # noqa: BLE001 -- broad on purpose; recorded, not swallowed
            failures.append({"service": name, "import_path": entry["import_path"],
                             "error": repr(exc)})
            continue
        router = getattr(mod, "router", None)
        if router is None:
            skipped.append(name)
            continue
        try:
            app.include_router(router)
        except Exception as exc:  # noqa: BLE001
            failures.append({"service": name, "import_path": entry["import_path"],
                             "error": "include_router failed: " + repr(exc)})
            continue
        mounted.append(name)
    try:
        app.state.spine_mounted = mounted
        app.state.spine_skipped_no_router = skipped
        app.state.spine_mount_failures = failures
        app.state.spine_service_count = len(SPINE_MOUNTS)
    except Exception:  # pragma: no cover - app.state always present on FastAPI
        pass
    if skipped:
        _log.warning("spine: %d active service(s) declare no router (skipped): %r",
                     len(skipped), skipped)
    if failures:
        _log.error("SPINE MOUNT FAILURES (%d of %d): %r",
                   len(failures), len(SPINE_MOUNTS), failures)
        if strict:
            raise RuntimeError("spine mount failures: %r" % (failures,))
    return {"mounted": mounted, "skipped_no_router": skipped, "failures": failures}
