# Auto-emitted service package __init__.py
# DO NOT EDIT - Generated by builder engine

from __future__ import annotations

import os
import sys
from typing import Generator, Optional

from fastapi import Depends, FastAPI
from sqlalchemy import create_engine
from sqlalchemy.orm import Session, sessionmaker
from sqlalchemy.pool import StaticPool

__version__ = "1.0.0"

SERVICE_NAME = os.environ.get("SERVICE_NAME", "zo-sentinel")
IS_STAGED = os.environ.get("STAGED_ENVIRONMENT", "").lower() in ("1", "true", "yes")

# Service-level config
SERVICE_HOST = os.environ.get("SERVICE_HOST", "0.0.0.0")
SERVICE_PORT = int(os.environ.get("SERVICE_PORT", "8080"))

# App DB config (authoritative source: app Postgres)
APP_DB_URL = os.environ.get(
    "APP_DATABASE_URL",
    "postgresql://localhost/mcp_app"
)

# Mesh/Computer store config
MESH_API_URL = os.environ.get("MESH_API_URL", "http://127.0.0.1:8772")
COMPUTER_STORE_URL = os.environ.get("COMPUTER_STORE_URL", "http://127.0.0.1:8772")

# Create engine with connection pooling
_engine = None
_SessionLocal = None

def get_engine():
    global _engine
    if _engine is None:
        _engine = create_engine(
            APP_DB_URL,
            pool_size=10,
            max_overflow=20,
            pool_pre_ping=True,
        )
    return _engine

def get_session_factory():
    global _SessionLocal
    if _SessionLocal is None:
        _SessionLocal = sessionmaker(
            autocommit=False,
            autoflush=False,
            bind=get_engine()
        )
    return _SessionLocal

def get_db() -> Generator[Session, None, None]:
    """Dependency for FastAPI routes - yields a DB session."""
    factory = get_session_factory()
    db = factory()
    try:
        yield db
    finally:
        db.close()

def get_current_session() -> Session:
    """Get current session without dependency injection context."""
    factory = get_session_factory()
    return factory()

# Re-export commonly used symbols
from app.db import get_session as _get_session
from app.models import (
    McpServerRegistry,
    McpLlmAxisScore,
    McpScoreDispute,
    VulnAdvisory,
    Org,
    User,
)

__all__ = [
    # Version and identity
    "__version__",
    "SERVICE_NAME",
    "IS_STAGED",
    "SERVICE_HOST",
    "SERVICE_PORT",
    # DB infrastructure
    "get_engine",
    "get_session_factory",
    "get_db",
    "get_current_session",
    "APP_DB_URL",
    # Mesh/API
    "MESH_API_URL",
    "COMPUTER_STORE_URL",
    # Models
    "McpServerRegistry",
    "McpLlmAxisScore",
    "McpScoreDispute",
    "VulnAdvisory",
    "Org",
    "User",
]

# FastAPI app factory for service module
def create_app() -> FastAPI:
    """Create and configure the FastAPI application for this service."""
    app = FastAPI(
        title=SERVICE_NAME,
        version=__version__,
        description=f"Auto-emitted service package for {SERVICE_NAME}",
    )
    return app

# Self-test entry point
if __name__ == "__main__":
    import json
    from fastapi.testclient import TestClient

    errors = []

    # Test 1: Module imports
    try:
        from app.db import get_session
        from app.models import (
            McpServerRegistry,
            McpLlmAxisScore,
            McpScoreDispute,
            VulnAdvisory,
            Org,
            User,
        )
    except ImportError as e:
        errors.append(f"Import error: {e}")

    # Test 2: In-memory DB for self-test (no app.db StaticPool)
    try:
        test_engine = create_engine(
            "sqlite:///:memory:",
            connect_args={"check_same_thread": False},
            poolclass=StaticPool,
        )
        TestSessionLocal = sessionmaker(
            autocommit=False, autoflush=False, bind=test_engine
        )

        def override_get_session():
            db = TestSessionLocal()
            try:
                yield db
            finally:
                db.close()

        # Create test app
        test_app = FastAPI(title="self-test")

        @test_app.get("/health")
        def health():
            return {"status": "ok", "version": __version__}

        @test_app.get("/db-test")
        def db_test(session: Session = Depends(override_get_session)):
            return {"db": "connected"}

        client = TestClient(test_app)
        
        # Verify health endpoint
        resp = client.get("/health")
        if resp.status_code != 200:
            errors.append(f"Health check failed: {resp.status_code}")
        
        # Verify DB dependency override
        resp = client.get("/db-test")
        if resp.status_code != 200:
            errors.append(f"DB test failed: {resp.status_code}")
        data = resp.json()
        if data.get("db") != "connected":
            errors.append(f"DB connection not working: {data}")

    except Exception as e:
        errors.append(f"Test harness error: {e}")

    # Test 3: Symbol table completeness
    required_symbols = [
        "get_db",
        "get_session_factory",
        "get_current_session",
        "McpServerRegistry",
        "McpLlmAxisScore",
        "McpScoreDispute",
        "VulnAdvisory",
    ]
    for sym in required_symbols:
        if sym not in globals():
            errors.append(f"Missing symbol: {sym}")

    if errors:
        print("FAIL")
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        sys.exit(1)
    else:
        print("PASS")