[service]
name = "cadence_job_health_consumer"
import_path = "services.active.cadence_job_health_consumer.router"
prefix = "/api"
tag = "cadence_job_health_consumer"
origin = "service"
auth = "public"
needs_data_layer = true