-- =====================================================================
-- app.sql  --  ZO SENTINEL APPLICATION SCHEMA  (OWNER: the app)
-- =====================================================================
-- The product's storage: the data served by the 5-endpoint API
-- (ui_server / bulk_assess_api / forensic_detail_api), the user UI, and
-- the admin UI. Workload is OLTP -- concurrent transactional reads/writes,
-- auth, and atomic (decision + audit_log) pairs.
--
-- TARGET ENGINE: DuckDB today (behind write_service :8772) -> Postgres.
-- This is the migration subset. The DDL below is the CURRENT live DuckDB
-- DDL, verbatim, with `-- PORTABILITY:` notes marking each DuckDB-ism and
-- its Postgres equivalent. The app schema is highly portable: native types
-- throughout, only three deltas (uuid default, sequences, caller-side
-- INSERT OR IGNORE).
--
-- All access goes through the write_service bus contract (/write,
-- /execute, /query) -- NEVER a direct duckdb/psycopg import in app code.
-- Source of truth extracted from full_schema_bootstrap.py (Phase A split).
-- =====================================================================

-- ---------------------------------------------------------------------
-- Sequences (app surrogate keys)
-- PORTABILITY: Postgres has native CREATE SEQUENCE; or replace the
-- `BIGINT DEFAULT nextval('seq')` columns with `BIGINT GENERATED BY
-- DEFAULT AS IDENTITY` and drop these.
-- ---------------------------------------------------------------------
CREATE SEQUENCE IF NOT EXISTS seq_signal_id   START 1;
CREATE SEQUENCE IF NOT EXISTS seq_threat_id   START 1;
CREATE SEQUENCE IF NOT EXISTS seq_decision_id START 1;
CREATE SEQUENCE IF NOT EXISTS seq_policy_id   START 1;
CREATE SEQUENCE IF NOT EXISTS seq_defhist_id  START 1;
CREATE SEQUENCE IF NOT EXISTS seq_id          START 1;

-- ---------------------------------------------------------------------
-- Core registry + assessment
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mcp_server_registry (
    server_id         VARCHAR PRIMARY KEY,
    name              VARCHAR,
    registry_source   VARCHAR,
    url               VARCHAR,
    description       TEXT,
    trust_score       FLOAT,
    verdict           VARCHAR,
    verdict_reasoning TEXT,
    confidence        FLOAT,
    last_assessed     TIMESTAMPTZ,
    first_seen        TIMESTAMPTZ,
    last_seen         TIMESTAMPTZ,
    last_scanned      TIMESTAMPTZ,
    scan_count        INTEGER DEFAULT 0,
    risk_tier         VARCHAR,
    metadata          TEXT
);

-- Long-format signal scores. PK(id) + UNIQUE(server_id, signal_name) are
-- REQUIRED for the callers' INSERT ... ON CONFLICT upserts (DuckDB raises
-- a Binder Error without them). See full_schema_bootstrap HISTORY 2026-04-17.
CREATE TABLE IF NOT EXISTS mcp_signal_scores (
    id          BIGINT PRIMARY KEY DEFAULT nextval('seq_signal_id'),
    server_id   VARCHAR NOT NULL,
    signal_name VARCHAR NOT NULL,
    score       FLOAT,
    evidence    TEXT,
    scored_at   TIMESTAMPTZ DEFAULT now(),
    UNIQUE (server_id, signal_name)
);

-- Callers (threat_intel_ingestor, rug_pull_monitor, pi_scorer) MUST set
-- `source` explicitly so UNIQUE(server_id, threat_type, source) dedupes.
CREATE TABLE IF NOT EXISTS mcp_threat_associations (
    id          BIGINT PRIMARY KEY DEFAULT nextval('seq_threat_id'),
    server_id   VARCHAR NOT NULL,
    threat_type VARCHAR NOT NULL,
    severity    VARCHAR,
    evidence    TEXT,
    source      VARCHAR,
    reported_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE (server_id, threat_type, source)
);

CREATE INDEX IF NOT EXISTS idx_signal_scores_server ON mcp_signal_scores(server_id);
CREATE INDEX IF NOT EXISTS idx_signal_scores_name   ON mcp_signal_scores(signal_name);
CREATE INDEX IF NOT EXISTS idx_threats_server       ON mcp_threat_associations(server_id);
CREATE INDEX IF NOT EXISTS idx_threats_severity     ON mcp_threat_associations(severity);

-- Per-server assessment artifacts (served by the forensic API).
CREATE TABLE IF NOT EXISTS mcp_tool_hashes (
    server_id    VARCHAR PRIMARY KEY,
    tools_hash   VARCHAR,
    tools_raw    TEXT,
    last_checked TIMESTAMPTZ DEFAULT now(),
    change_count INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS mcp_fingerprints (
    server_id             VARCHAR PRIMARY KEY,
    tool_name_hash        VARCHAR,
    description_tokens    TEXT,
    permission_scope_hash VARCHAR,
    domain_fingerprint    VARCHAR,
    version_string        VARCHAR,
    computed_at           TIMESTAMPTZ DEFAULT now()
);

-- ---------------------------------------------------------------------
-- Discovery + enrichment  (ADOPTED 2026-06-10 -- previously flagged as
-- schema drift by the app-model graph because they predate this split, but
-- they are real product tables: the pathway/funnel endpoint counts both,
-- and the enrichment subsystem feeds signal assessment.)
-- PORTABILITY: JSON -> Postgres jsonb; DOUBLE -> double precision;
--   `INTERVAL 30 days` -> Postgres `INTERVAL '30 days'`.
-- ---------------------------------------------------------------------

-- Pre-registry discovery funnel (PyPI / registry ingestors -> candidates).
-- CANON NOTE: 4 files define this table with TWO different PK shapes --
-- discovery_pypi_paginator_v2 uses `server_id VARCHAR PK` (repo convention,
-- adopted here) vs mcp_directory_ingestor's `candidate_id INTEGER PK`. The
-- ingestors should converge on THIS shape; app.sql is the canon they match.
CREATE TABLE IF NOT EXISTS mcp_discovery_candidates (
    server_id           VARCHAR PRIMARY KEY,
    source              VARCHAR NOT NULL,
    name                VARCHAR NOT NULL,
    version             VARCHAR,
    description         TEXT,
    author              VARCHAR,
    author_email        VARCHAR,
    url                 VARCHAR,
    repository          VARCHAR,
    license             VARCHAR,
    keywords            VARCHAR,
    created_at          VARCHAR,
    latest_release      VARCHAR,
    downloads_last_week BIGINT,
    ingested_at         VARCHAR NOT NULL,
    status              VARCHAR DEFAULT 'pending',
    metadata            JSON
);

-- Signal enrichments (supply-chain / community / ecosystem scores that enrich
-- mcp_signal_scores). Written by enrichment daemons, read by assessment + the
-- pathway endpoint. evidence is JSON; rows carry a 30-day TTL.
CREATE TABLE IF NOT EXISTS mcp_signal_enrichments (
    id              BIGINT PRIMARY KEY,
    mcp_server_id   VARCHAR NOT NULL,
    enrichment_type VARCHAR NOT NULL,
    score           DOUBLE,
    evidence        JSON,
    computed_at     TIMESTAMPTZ DEFAULT now(),
    expires_at      TIMESTAMPTZ DEFAULT (now() + INTERVAL 30 days)
);
CREATE INDEX IF NOT EXISTS idx_enrichments_server_type
    ON mcp_signal_enrichments (mcp_server_id, enrichment_type);

-- ---------------------------------------------------------------------
-- Intake -> decision -> policy  (the analyst workflow the admin UI drives)
-- ---------------------------------------------------------------------
-- PORTABILITY: `gen_random_uuid()::VARCHAR` -> Postgres `gen_random_uuid()`
-- (pgcrypto / built-in in PG13+) returns uuid; cast `::text`.
CREATE TABLE IF NOT EXISTS mcp_submissions (
    submission_id    VARCHAR PRIMARY KEY DEFAULT gen_random_uuid()::VARCHAR,
    server_id        VARCHAR,
    mcp_name         VARCHAR NOT NULL,
    url              VARCHAR,
    description      TEXT,
    requested_by     VARCHAR,
    business_purpose TEXT,
    environment      VARCHAR,
    submitted_at     TIMESTAMPTZ DEFAULT now(),
    status           VARCHAR DEFAULT 'pending'
);

CREATE TABLE IF NOT EXISTS mcp_decisions (
    id            BIGINT DEFAULT nextval('seq_decision_id'),
    submission_id VARCHAR,
    analyst_name  VARCHAR,
    decision      VARCHAR,
    conditions    TEXT,
    notes         TEXT,
    expiry_days   INTEGER DEFAULT 90,
    expires_at    TIMESTAMPTZ,
    decided_at    TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS mcp_policy_rules (
    id          BIGINT DEFAULT nextval('seq_policy_id'),
    rule_name   VARCHAR UNIQUE NOT NULL,
    rule_type   VARCHAR,
    pattern     VARCHAR,
    action      VARCHAR,
    description TEXT,
    created_at  TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS mcp_definition_history (
    id            BIGINT DEFAULT nextval('seq_defhist_id'),
    server_id     VARCHAR,
    snapshot_hash VARCHAR,
    captured_at   TIMESTAMPTZ DEFAULT now()
);

-- ---------------------------------------------------------------------
-- Risk, attestation, audit  (served to forensic API + admin UI)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS mcp_risk_register (
    server_id            VARCHAR PRIMARY KEY,
    name                 VARCHAR,
    risk_rank            FLOAT,
    risk_tier            VARCHAR,
    threat_count         INTEGER DEFAULT 0,
    staleness_days       INTEGER DEFAULT 0,
    environment_exposure VARCHAR DEFAULT 'unknown',
    computed_at          TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS mcp_attestations (
    attestation_id   VARCHAR PRIMARY KEY DEFAULT gen_random_uuid()::VARCHAR,
    server_id        VARCHAR NOT NULL,
    attestation_text TEXT,
    scope            VARCHAR,
    confidence_level FLOAT,
    valid_until      TIMESTAMPTZ,
    risk_tier        VARCHAR,
    caveats          TEXT,
    status           VARCHAR DEFAULT 'active',
    generated_at     TIMESTAMPTZ DEFAULT now()
);

-- Immutable audit trail. The admin UI writes here on every mutation
-- (revoke/extend/exempt); a decision and its audit row should be ATOMIC --
-- a transactional guarantee DuckDB's single writer fakes by serialization
-- and Postgres provides natively (the OLTP argument for the migration).
CREATE TABLE IF NOT EXISTS audit_log (
    event_id         VARCHAR PRIMARY KEY DEFAULT gen_random_uuid()::VARCHAR,
    event_type       VARCHAR,
    actor            VARCHAR,
    target_server_id VARCHAR,
    action           VARCHAR,
    outcome          VARCHAR,
    details_json     TEXT,
    immutable        BOOLEAN DEFAULT TRUE,
    timestamp        TIMESTAMPTZ DEFAULT now()
);

-- Analyst-granted exemptions (managed in the admin UI: admin_exemptions.html).
CREATE TABLE IF NOT EXISTS mcp_exemptions (
    exemption_id    VARCHAR PRIMARY KEY DEFAULT gen_random_uuid()::VARCHAR,
    server_id       VARCHAR NOT NULL,
    reason          TEXT,
    granted_by      VARCHAR,
    conditions_json TEXT,
    expires_at      TIMESTAMPTZ,
    active          BOOLEAN DEFAULT TRUE,
    created_at      TIMESTAMPTZ DEFAULT now()
);

-- ---------------------------------------------------------------------
-- Auth  (token-based, scope-enforced -- the admin gate)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS auth_tokens (
    token_id      VARCHAR PRIMARY KEY,
    action        VARCHAR,
    mcp_name      VARCHAR,
    submission_id VARCHAR,
    requested_by  VARCHAR,
    admin_email   VARCHAR,
    expires_at    TIMESTAMPTZ,
    used          BOOLEAN DEFAULT FALSE,
    used_at       TIMESTAMPTZ,
    created_at    TIMESTAMPTZ DEFAULT now()
);

-- ---------------------------------------------------------------------
-- Telemetry + external enrichment feeds
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS perf_metrics (
    service     VARCHAR,
    latency_ms  FLOAT,
    recorded_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS shodan_results (
    server_id      VARCHAR,
    ip_address     VARCHAR,
    open_ports     TEXT,
    cves_found     TEXT,
    exposure_score FLOAT,
    scanned_at     TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS github_velocity (
    server_id              VARCHAR,
    repo_url               VARCHAR,
    commit_velocity        FLOAT,
    contributor_churn      FLOAT,
    last_suspicious_commit VARCHAR,
    checked_at             TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS npm_typosquat_alerts (
    id               BIGINT DEFAULT nextval('seq_id'),
    suspect_name     VARCHAR,
    target_name      VARCHAR,
    levenshtein_dist INTEGER,
    npm_downloads    INTEGER DEFAULT 0,
    published_at     TIMESTAMPTZ,
    flagged_at       TIMESTAMPTZ DEFAULT now()
);

-- =====================================================================
-- CALLER-SIDE PORTABILITY (not DDL, but the bus router must translate):
--   DuckDB `INSERT OR IGNORE INTO t ...`
--     -> Postgres `INSERT INTO t ... ON CONFLICT DO NOTHING`
--   DuckDB `INSERT ... ON CONFLICT (cols) DO UPDATE` is already PG-compatible.
-- Everything else here (TIMESTAMPTZ, TEXT, FLOAT, BIGINT, BOOLEAN, now(),
-- CREATE INDEX IF NOT EXISTS, DEFAULT TRUE) is native in both engines.
-- =====================================================================
