-- app_graph.sql -- GENERATED by tools/build_app_graph.py from capmap.json
-- The app-model knowledge graph: node/edge tables + completeness queries.
-- Re-generate after refreshing capmap.json. Plain-SQL views need no extension.

DROP TABLE IF EXISTS app_edge; DROP TABLE IF EXISTS app_node;
CREATE TABLE app_node (
  id VARCHAR PRIMARY KEY, kind VARCHAR, name VARCHAR, area VARCHAR, file VARCHAR,
  status VARCHAR, served BOOLEAN, reaches_storage BOOLEAN, is_bug BOOLEAN, detail VARCHAR);
CREATE TABLE app_edge (src VARCHAR, dst VARCHAR, rel VARCHAR);

INSERT INTO app_node VALUES ('area:Registry/Assessment','area','Registry/Assessment','Registry/Assessment','','partial',NULL,NULL,NULL,'registry endpoints are well-wired across 3 servers, but all 4 registry/detail UIs are orphaned; ui_server /api/servers selects last_scan which is not a column in mcp_server_registry (schema is last_scanned); mcp_detail_view_ui.py serves inline HTML instead of the 3 detail_view .html files');
INSERT INTO app_node VALUES ('table:mcp_server_registry','table','mcp_server_registry','Manual Override','','',NULL,NULL,NULL,'');
INSERT INTO app_node VALUES ('table:mcp_signal_scores','table','mcp_signal_scores','Pathway/Funnel','','',NULL,NULL,NULL,'');
INSERT INTO app_node VALUES ('table:mcp_threat_associations','table','mcp_threat_associations','Risk/Forensics','','',NULL,NULL,NULL,'');
INSERT INTO app_node VALUES ('table:mcp_fingerprints','table','mcp_fingerprints','Pathway/Funnel','','',NULL,NULL,NULL,'');
INSERT INTO app_node VALUES ('table:mcp_tool_hashes','table','mcp_tool_hashes','Registry/Assessment','','',NULL,NULL,NULL,'');
INSERT INTO app_node VALUES ('ep:GET:/api/servers','endpoint','GET /api/servers','Registry/Assessment','ui_server.py','',NULL,TRUE,TRUE,'reads mcp_server_registry (selects last_scan col not in schema)');
INSERT INTO app_node VALUES ('ep:GET:/api/servers/{server_id}','endpoint','GET /api/servers/{server_id}','Registry/Assessment','ui_server.py','',NULL,TRUE,FALSE,'reads mcp_server_registry + mcp_signal_scores');
INSERT INTO app_node VALUES ('ep:GET:/v1/registry','endpoint','GET /v1/registry','Registry/Assessment','registry_api.py','',NULL,TRUE,FALSE,'reads mcp_server_registry');
INSERT INTO app_node VALUES ('ep:GET:/v1/assess','endpoint','GET /v1/assess','Registry/Assessment','registry_api.py','',NULL,TRUE,FALSE,'reads registry+signals+threats+attestations');
INSERT INTO app_node VALUES ('ep:GET:/v1/threats','endpoint','GET /v1/threats','Registry/Assessment','registry_api.py','',NULL,TRUE,FALSE,'reads mcp_threat_associations join registry');
INSERT INTO app_node VALUES ('ep:POST:/v1/bulk/assess','endpoint','POST /v1/bulk/assess','Registry/Assessment','bulk_assess_api.py','',NULL,TRUE,FALSE,'reads mcp_server_registry, writes bulk_assess_jobs');
INSERT INTO app_node VALUES ('table:bulk_assess_jobs','table','bulk_assess_jobs','Registry/Assessment','','',NULL,NULL,NULL,'NOT in app.sql (drift)');
INSERT INTO app_node VALUES ('ep:POST:/v1/bulk/import','endpoint','POST /v1/bulk/import','Registry/Assessment','bulk_assess_api.py','',NULL,TRUE,FALSE,'writes mcp_server_registry, bulk_imports');
INSERT INTO app_node VALUES ('ep:GET:/v1/export/csv','endpoint','GET /v1/export/csv','Registry/Assessment','bulk_assess_api.py','',NULL,TRUE,FALSE,'reads mcp_server_registry');
INSERT INTO app_node VALUES ('ui:sentinel_status.html','uipage','sentinel_status.html','Registry/Assessment','','',FALSE,NULL,NULL,'calls /v1/registry,/v1/threats but no FileResponse/StaticFiles/route serves this file');
INSERT INTO app_node VALUES ('ui:mcp_detail_view.html','uipage','mcp_detail_view.html','Registry/Assessment','','',FALSE,NULL,NULL,'orphaned; mcp_detail_view_ui.py returns its own INLINE HTMLResponse, never this file');
INSERT INTO app_node VALUES ('ui:mcp_detail_view_ui.html','uipage','mcp_detail_view_ui.html','Registry/Assessment','','',FALSE,NULL,NULL,'orphaned; no route references it');
INSERT INTO app_node VALUES ('ui:mcp_detail_view_ui_v2.html','uipage','mcp_detail_view_ui_v2.html','Registry/Assessment','','',FALSE,NULL,NULL,'orphaned; posts to 8781/write directly, no serving route');
INSERT INTO app_node VALUES ('area:Submissions','area','Submissions','Submissions','','partial',NULL,NULL,NULL,'submission portal + admin_submissions HTML are both orphaned (no serving route); ui_server.py /api/submissions reads/writes the WRONG table (mesh_events) so it never sees real submissions; admin_submissions.html calls /v1/submissions which no server defines; approval_workflow writes submission columns that do not match app.sql schema');
INSERT INTO app_node VALUES ('table:mcp_submissions','table','mcp_submissions','Decisions','','',NULL,NULL,NULL,'');
INSERT INTO app_node VALUES ('ep:POST:/api/submit','endpoint','POST /api/submit','Submissions','approval_workflow.py','',NULL,TRUE,TRUE,'writes mcp_submissions (cols mcp_identifier/requester_name/requester_team mismatch schema mcp_name/requested_by)');
INSERT INTO app_node VALUES ('ep:GET:/api/submission/{id}','endpoint','GET /api/submission/{id}','Submissions','approval_workflow.py','',NULL,TRUE,FALSE,'reads mcp_submissions + mcp_decisions');
INSERT INTO app_node VALUES ('table:mcp_decisions','table','mcp_decisions','Decisions','','',NULL,NULL,NULL,'');
INSERT INTO app_node VALUES ('ep:GET:/api/submissions','endpoint','GET /api/submissions','Submissions','ui_server.py','',NULL,FALSE,TRUE,'queries mesh_events (WRONG table) not mcp_submissions; returns nothing for submissions');
INSERT INTO app_node VALUES ('table:mesh_events','table','mesh_events','Submissions','','',NULL,NULL,NULL,'NOT in app.sql (drift)');
INSERT INTO app_node VALUES ('ep:POST:/api/submissions','endpoint','POST /api/submissions','Submissions','ui_server.py','',NULL,FALSE,TRUE,'writes mesh_events (WRONG table) not mcp_submissions');
INSERT INTO app_node VALUES ('ui:mcp_submission_portal.html','uipage','mcp_submission_portal.html','Submissions','','',FALSE,NULL,NULL,'calls /api/submit (which exists in approval_workflow.py) but the portal HTML itself is orphaned - no route serves it');
INSERT INTO app_node VALUES ('ui:admin_submissions.html','uipage','admin_submissions.html','Submissions','','',FALSE,NULL,NULL,'orphaned; calls /v1/submissions (NO such endpoint exists) and bus :8772/query directly');
INSERT INTO app_node VALUES ('area:Decisions','area','Decisions','Decisions','','partial',NULL,NULL,NULL,'decision recording is wired to storage but has NO dedicated UI - analysts must hit the API directly (admin_submissions.html does not call /api/decision)');
INSERT INTO app_node VALUES ('ep:POST:/api/decision/{submission_id}','endpoint','POST /api/decision/{submission_id}','Decisions','approval_workflow.py','',NULL,TRUE,FALSE,'writes mcp_decisions + updates mcp_submissions.status');
INSERT INTO app_node VALUES ('ep:GET:/api/audit','endpoint','GET /api/audit','Decisions','approval_workflow.py','',NULL,TRUE,FALSE,'reads mcp_decisions join mcp_submissions');
INSERT INTO app_node VALUES ('area:Policies','area','Policies','Policies','','gap',NULL,NULL,NULL,'only endpoint (/api/policies) queries the WRONG table (policy_rules vs schema mcp_policy_rules) so reaches_storage effectively false; no POST/create-policy endpoint exists; admin_policies.html is orphaned and bypasses the API to write the bus directly');
INSERT INTO app_node VALUES ('table:mcp_policy_rules','table','mcp_policy_rules','Policies','','',NULL,NULL,NULL,'');
INSERT INTO app_node VALUES ('ep:GET:/api/policies','endpoint','GET /api/policies','Policies','ui_server.py','',NULL,FALSE,TRUE,'queries policy_rules (WRONG table) not mcp_policy_rules; also selects policy_id/rule_json cols absent from schema');
INSERT INTO app_node VALUES ('table:policy_rules','table','policy_rules','Policies','','',NULL,NULL,NULL,'NOT in app.sql (drift)');
INSERT INTO app_node VALUES ('ui:admin_policies.html','uipage','admin_policies.html','Policies','','',FALSE,NULL,NULL,'orphaned; talks directly to bus :8772/query and /execute, no API endpoint and no serving route');
INSERT INTO app_node VALUES ('area:Attestations','area','Attestations','Attestations','','partial',NULL,NULL,NULL,'both read endpoints select column names that do not match app.sql (schema uses attestation_text/scope/valid_until/status); queries likely error or return empty; no create-attestation HTTP endpoint; admin_attestations.html is orphaned and bypasses the API');
INSERT INTO app_node VALUES ('table:mcp_attestations','table','mcp_attestations','Pathway/Funnel','','',NULL,NULL,NULL,'');
INSERT INTO app_node VALUES ('ep:GET:/api/attestations','endpoint','GET /api/attestations','Attestations','ui_server.py','',NULL,TRUE,TRUE,'reads mcp_attestations (selects server_name/attested_at cols absent from schema)');
INSERT INTO app_node VALUES ('ep:GET:/servers/{server_id}/attestations','endpoint','GET /servers/{server_id}/attestations','Attestations','forensic_detail_api_v2.py','',NULL,TRUE,TRUE,'reads mcp_attestations (selects attestation_type/attested_by/expiry_date cols absent from schema)');
INSERT INTO app_node VALUES ('ui:admin_attestations.html','uipage','admin_attestations.html','Attestations','','',FALSE,NULL,NULL,'orphaned; calls attestation engine /revoke (:8780) and bus :8772 query/execute/write directly, no serving route');
INSERT INTO app_node VALUES ('area:Exemptions','area','Exemptions','Exemptions','','gap',NULL,NULL,NULL,'NO HTTP endpoint anywhere reads or writes mcp_exemptions (exemption_manager.py is a library, not a FastAPI server); admin_exemptions.html is orphaned and reaches storage only by posting raw SQL to the bus');
INSERT INTO app_node VALUES ('table:mcp_exemptions','table','mcp_exemptions','Exemptions','','',NULL,NULL,NULL,'');
INSERT INTO app_node VALUES ('ui:admin_exemptions.html','uipage','admin_exemptions.html','Exemptions','','',FALSE,NULL,NULL,'orphaned; only talks to bus :8772/query directly, no API endpoint exists and no route serves the file');
INSERT INTO app_node VALUES ('area:Risk/Forensics','area','Risk/Forensics','Risk/Forensics','','partial',NULL,NULL,NULL,'forensic API is well-wired (touches risk_register, signals, threats, audit) but mcp_detail_view*.html that would render it are all orphaned (see Registry area); shodan_results/github_velocity/npm_typosquat_alerts tables have NO endpoint exposing them to any UI; forensic verdict-history query selects reasoning col not present in mcp_risk_register');
INSERT INTO app_node VALUES ('table:mcp_risk_register','table','mcp_risk_register','Dashboard/Summary','','',NULL,NULL,NULL,'');
INSERT INTO app_node VALUES ('table:shodan_results','table','shodan_results','Risk/Forensics','','',NULL,NULL,NULL,'');
INSERT INTO app_node VALUES ('table:github_velocity','table','github_velocity','Risk/Forensics','','',NULL,NULL,NULL,'');
INSERT INTO app_node VALUES ('table:npm_typosquat_alerts','table','npm_typosquat_alerts','Risk/Forensics','','',NULL,NULL,NULL,'');
INSERT INTO app_node VALUES ('ep:GET:/servers/{server_id}/forensic','endpoint','GET /servers/{server_id}/forensic','Risk/Forensics','forensic_detail_api_v2.py','',NULL,TRUE,FALSE,'reads registry+signals+threats+attestations+mcp_risk_register+audit_log');
INSERT INTO app_node VALUES ('table:audit_log','table','audit_log','Manual Override','','',NULL,NULL,NULL,'');
INSERT INTO app_node VALUES ('ep:GET:/servers/{server_id}/signals','endpoint','GET /servers/{server_id}/signals','Risk/Forensics','forensic_detail_api_v2.py','',NULL,TRUE,FALSE,'reads mcp_signal_scores');
INSERT INTO app_node VALUES ('ep:GET:/servers/{server_id}/threats','endpoint','GET /servers/{server_id}/threats','Risk/Forensics','forensic_detail_api_v2.py','',NULL,TRUE,FALSE,'reads mcp_threat_associations');
INSERT INTO app_node VALUES ('ep:GET:/risks','endpoint','GET /risks','Risk/Forensics','search_api.py','',NULL,TRUE,FALSE,'reads mcp_risk_register');
INSERT INTO app_node VALUES ('area:Audit','area','Audit','Audit','','partial',NULL,NULL,NULL,'audit read/write endpoints exist and reach storage, but no dedicated audit UI is served; ui_server query selects id/detail columns that mismatch schema (event_id/details_json)');
INSERT INTO app_node VALUES ('ep:GET:/api/audit-log','endpoint','GET /api/audit-log','Audit','ui_server.py','',NULL,TRUE,FALSE,'reads audit_log (selects id/detail cols; schema uses event_id/details_json)');
INSERT INTO app_node VALUES ('ep:GET:/audit/events','endpoint','GET /audit/events','Audit','registry_api_v2.py','',NULL,TRUE,FALSE,'reads audit_log');
INSERT INTO app_node VALUES ('ep:POST:/audit','endpoint','POST /audit','Audit','registry_api_v2.py','',NULL,TRUE,FALSE,'writes audit_log');
INSERT INTO app_node VALUES ('area:Auth','area','Auth','Auth','','partial',NULL,NULL,NULL,'auth is fully wired to auth_tokens with admin-scope gating, but there is NO token-management UI; tokens must be created/revoked via raw API calls');
INSERT INTO app_node VALUES ('table:auth_tokens','table','auth_tokens','Auth','','',NULL,NULL,NULL,'');
INSERT INTO app_node VALUES ('ep:GET:/api/auth/check','endpoint','GET /api/auth/check','Auth','ui_server.py','',NULL,FALSE,TRUE,'reads request.state token only');
INSERT INTO app_node VALUES ('ep:POST:/api/auth/token','endpoint','POST /api/auth/token','Auth','ui_server.py','',NULL,TRUE,FALSE,'writes auth_tokens');
INSERT INTO app_node VALUES ('ep:GET:/api/auth/tokens','endpoint','GET /api/auth/tokens','Auth','ui_server.py','',NULL,TRUE,FALSE,'reads auth_tokens');
INSERT INTO app_node VALUES ('ep:DELETE:/api/auth/tokens/{token_id}','endpoint','DELETE /api/auth/tokens/{token_id}','Auth','ui_server.py','',NULL,TRUE,FALSE,'updates auth_tokens (revoke)');
INSERT INTO app_node VALUES ('area:Dashboard/Summary','area','Dashboard/Summary','Dashboard/Summary','','partial',NULL,NULL,NULL,'summary/dashboard endpoints are wired across ui_server + dashboard_api, but the only SERVED html (dashboard.html) is a build-watcher dev page, not the product dashboard; the real product dashboard/pathway/builder-eye HTMLs are all orphaned');
INSERT INTO app_node VALUES ('ep:GET:/api/dashboard/summary','endpoint','GET /api/dashboard/summary','Dashboard/Summary','ui_server.py','',NULL,TRUE,FALSE,'reads mcp_server_registry + mcp_risk_register counts');
INSERT INTO app_node VALUES ('ep:GET:/dashboard/summary','endpoint','GET /dashboard/summary','Dashboard/Summary','dashboard_api.py','',NULL,TRUE,FALSE,'reads registry/risk aggregates');
INSERT INTO app_node VALUES ('ep:GET:/dashboard/recent','endpoint','GET /dashboard/recent','Dashboard/Summary','dashboard_api.py','',NULL,TRUE,FALSE,'reads mcp_server_registry');
INSERT INTO app_node VALUES ('ep:GET:/dashboard/top_risks','endpoint','GET /dashboard/top_risks','Dashboard/Summary','dashboard_api.py','',NULL,TRUE,FALSE,'reads mcp_risk_register');
INSERT INTO app_node VALUES ('ep:GET:/dashboard/trends','endpoint','GET /dashboard/trends','Dashboard/Summary','dashboard_api.py','',NULL,TRUE,FALSE,'reads registry trends');
INSERT INTO app_node VALUES ('ui:dashboard.html','uipage','dashboard.html','Dashboard/Summary','','',TRUE,NULL,NULL,'build_watcher_api.py GET / returns FileResponse(dashboard.html) - but it is a BUILD-WATCHER dev page wired to /api/build-stream, NOT the product summary dashboard');
INSERT INTO app_node VALUES ('ui:builder_eye_dashboard.html','uipage','builder_eye_dashboard.html','Dashboard/Summary','','',FALSE,NULL,NULL,'orphaned; calls 8795/api/build-stream, no route serves the file');
INSERT INTO app_node VALUES ('ui:builder_eye_dashboard_public.html','uipage','builder_eye_dashboard_public.html','Dashboard/Summary','','',FALSE,NULL,NULL,'orphaned; no serving route');
INSERT INTO app_node VALUES ('ui:builder_eye_dashboard_hr.html','uipage','builder_eye_dashboard_hr.html','Dashboard/Summary','','',FALSE,NULL,NULL,'orphaned; no serving route');
INSERT INTO app_node VALUES ('ui:pathway_to_20k.html','uipage','pathway_to_20k.html','Pathway/Funnel','','',FALSE,NULL,NULL,'consumes all /api/pathway/* endpoints but is orphaned - no route serves it');
INSERT INTO app_node VALUES ('area:Pathway/Funnel','area','Pathway/Funnel','Pathway/Funnel','','partial',NULL,NULL,NULL,'pathway endpoints are fully wired but the consuming UI (pathway_to_20k.html) is orphaned; some counts query tables not in app.sql (mcp_discovery_candidates, mcp_signal_enrichments)');
INSERT INTO app_node VALUES ('ep:GET:/api/pathway/totals','endpoint','GET /api/pathway/totals','Pathway/Funnel','pathway_api.py','',NULL,TRUE,FALSE,'counts registry/fingerprints/signals/attestations (also mcp_discovery_candidates, mcp_signal_enrichments not in app.sql)');
INSERT INTO app_node VALUES ('table:mcp_signal_enrichments','table','mcp_signal_enrichments','Pathway/Funnel','','',NULL,NULL,NULL,'');
INSERT INTO app_node VALUES ('table:mcp_discovery_candidates','table','mcp_discovery_candidates','Pathway/Funnel','','',NULL,NULL,NULL,'');
INSERT INTO app_node VALUES ('ep:GET:/api/pathway/funnel','endpoint','GET /api/pathway/funnel','Pathway/Funnel','pathway_api.py','',NULL,TRUE,FALSE,'reads registry/fingerprints/signals velocity');
INSERT INTO app_node VALUES ('ep:GET:/api/pathway/velocity','endpoint','GET /api/pathway/velocity','Pathway/Funnel','pathway_api.py','',NULL,TRUE,FALSE,'reads registry/fingerprints/attestations hourly');
INSERT INTO app_node VALUES ('ep:GET:/api/pathway/eta','endpoint','GET /api/pathway/eta','Pathway/Funnel','pathway_api.py','',NULL,TRUE,FALSE,'computes from registry counts');
INSERT INTO app_node VALUES ('area:Manual Override','area','Manual Override','Manual Override','','partial',NULL,NULL,NULL,'override endpoints are wired to registry+audit_log but have NO UI; only reachable via direct API');
INSERT INTO app_node VALUES ('ep:POST:/override/trust','endpoint','POST /override/trust','Manual Override','manual_override_api.py','',NULL,TRUE,FALSE,'updates mcp_server_registry trust_score');
INSERT INTO app_node VALUES ('ep:POST:/override/verdict','endpoint','POST /override/verdict','Manual Override','manual_override_api.py','',NULL,TRUE,FALSE,'updates mcp_server_registry verdict');
INSERT INTO app_node VALUES ('ep:POST:/servers/{server_id}/override','endpoint','POST /servers/{server_id}/override','Manual Override','manual_override_api_v2.py','',NULL,TRUE,FALSE,'updates registry + writes audit_log');
INSERT INTO app_node VALUES ('ep:GET:/servers/{server_id}/override/history','endpoint','GET /servers/{server_id}/override/history','Manual Override','manual_override_api_v2.py','',NULL,TRUE,FALSE,'reads override history/audit_log');
INSERT INTO app_node VALUES ('ep:POST:/servers/{server_id}/override/revert','endpoint','POST /servers/{server_id}/override/revert','Manual Override','manual_override_api_v2.py','',NULL,TRUE,FALSE,'reverts registry override');

INSERT INTO app_edge VALUES ('area:Attestations','ep:GET:/api/attestations','has');
INSERT INTO app_edge VALUES ('area:Attestations','ep:GET:/servers/{server_id}/attestations','has');
INSERT INTO app_edge VALUES ('area:Attestations','table:mcp_attestations','has');
INSERT INTO app_edge VALUES ('area:Attestations','ui:admin_attestations.html','has');
INSERT INTO app_edge VALUES ('area:Audit','ep:GET:/api/audit-log','has');
INSERT INTO app_edge VALUES ('area:Audit','ep:GET:/audit/events','has');
INSERT INTO app_edge VALUES ('area:Audit','ep:POST:/audit','has');
INSERT INTO app_edge VALUES ('area:Audit','table:audit_log','has');
INSERT INTO app_edge VALUES ('area:Auth','ep:DELETE:/api/auth/tokens/{token_id}','has');
INSERT INTO app_edge VALUES ('area:Auth','ep:GET:/api/auth/check','has');
INSERT INTO app_edge VALUES ('area:Auth','ep:GET:/api/auth/tokens','has');
INSERT INTO app_edge VALUES ('area:Auth','ep:POST:/api/auth/token','has');
INSERT INTO app_edge VALUES ('area:Auth','table:auth_tokens','has');
INSERT INTO app_edge VALUES ('area:Dashboard/Summary','ep:GET:/api/dashboard/summary','has');
INSERT INTO app_edge VALUES ('area:Dashboard/Summary','ep:GET:/dashboard/recent','has');
INSERT INTO app_edge VALUES ('area:Dashboard/Summary','ep:GET:/dashboard/summary','has');
INSERT INTO app_edge VALUES ('area:Dashboard/Summary','ep:GET:/dashboard/top_risks','has');
INSERT INTO app_edge VALUES ('area:Dashboard/Summary','ep:GET:/dashboard/trends','has');
INSERT INTO app_edge VALUES ('area:Dashboard/Summary','table:mcp_risk_register','has');
INSERT INTO app_edge VALUES ('area:Dashboard/Summary','table:mcp_server_registry','has');
INSERT INTO app_edge VALUES ('area:Dashboard/Summary','ui:builder_eye_dashboard.html','has');
INSERT INTO app_edge VALUES ('area:Dashboard/Summary','ui:builder_eye_dashboard_hr.html','has');
INSERT INTO app_edge VALUES ('area:Dashboard/Summary','ui:builder_eye_dashboard_public.html','has');
INSERT INTO app_edge VALUES ('area:Dashboard/Summary','ui:dashboard.html','has');
INSERT INTO app_edge VALUES ('area:Dashboard/Summary','ui:dashboard.html','serves');
INSERT INTO app_edge VALUES ('area:Dashboard/Summary','ui:pathway_to_20k.html','has');
INSERT INTO app_edge VALUES ('area:Decisions','ep:GET:/api/audit','has');
INSERT INTO app_edge VALUES ('area:Decisions','ep:POST:/api/decision/{submission_id}','has');
INSERT INTO app_edge VALUES ('area:Decisions','table:mcp_decisions','has');
INSERT INTO app_edge VALUES ('area:Exemptions','table:mcp_exemptions','has');
INSERT INTO app_edge VALUES ('area:Exemptions','ui:admin_exemptions.html','has');
INSERT INTO app_edge VALUES ('area:Manual Override','ep:GET:/servers/{server_id}/override/history','has');
INSERT INTO app_edge VALUES ('area:Manual Override','ep:POST:/override/trust','has');
INSERT INTO app_edge VALUES ('area:Manual Override','ep:POST:/override/verdict','has');
INSERT INTO app_edge VALUES ('area:Manual Override','ep:POST:/servers/{server_id}/override','has');
INSERT INTO app_edge VALUES ('area:Manual Override','ep:POST:/servers/{server_id}/override/revert','has');
INSERT INTO app_edge VALUES ('area:Manual Override','table:audit_log','has');
INSERT INTO app_edge VALUES ('area:Manual Override','table:mcp_server_registry','has');
INSERT INTO app_edge VALUES ('area:Pathway/Funnel','ep:GET:/api/pathway/eta','has');
INSERT INTO app_edge VALUES ('area:Pathway/Funnel','ep:GET:/api/pathway/funnel','has');
INSERT INTO app_edge VALUES ('area:Pathway/Funnel','ep:GET:/api/pathway/totals','has');
INSERT INTO app_edge VALUES ('area:Pathway/Funnel','ep:GET:/api/pathway/velocity','has');
INSERT INTO app_edge VALUES ('area:Pathway/Funnel','table:mcp_attestations','has');
INSERT INTO app_edge VALUES ('area:Pathway/Funnel','table:mcp_fingerprints','has');
INSERT INTO app_edge VALUES ('area:Pathway/Funnel','table:mcp_server_registry','has');
INSERT INTO app_edge VALUES ('area:Pathway/Funnel','table:mcp_signal_scores','has');
INSERT INTO app_edge VALUES ('area:Pathway/Funnel','ui:pathway_to_20k.html','has');
INSERT INTO app_edge VALUES ('area:Policies','ep:GET:/api/policies','has');
INSERT INTO app_edge VALUES ('area:Policies','table:mcp_policy_rules','has');
INSERT INTO app_edge VALUES ('area:Policies','ui:admin_policies.html','has');
INSERT INTO app_edge VALUES ('area:Registry/Assessment','ep:GET:/api/servers','has');
INSERT INTO app_edge VALUES ('area:Registry/Assessment','ep:GET:/api/servers/{server_id}','has');
INSERT INTO app_edge VALUES ('area:Registry/Assessment','ep:GET:/v1/assess','has');
INSERT INTO app_edge VALUES ('area:Registry/Assessment','ep:GET:/v1/export/csv','has');
INSERT INTO app_edge VALUES ('area:Registry/Assessment','ep:GET:/v1/registry','has');
INSERT INTO app_edge VALUES ('area:Registry/Assessment','ep:GET:/v1/threats','has');
INSERT INTO app_edge VALUES ('area:Registry/Assessment','ep:POST:/v1/bulk/assess','has');
INSERT INTO app_edge VALUES ('area:Registry/Assessment','ep:POST:/v1/bulk/import','has');
INSERT INTO app_edge VALUES ('area:Registry/Assessment','table:mcp_fingerprints','has');
INSERT INTO app_edge VALUES ('area:Registry/Assessment','table:mcp_server_registry','has');
INSERT INTO app_edge VALUES ('area:Registry/Assessment','table:mcp_signal_scores','has');
INSERT INTO app_edge VALUES ('area:Registry/Assessment','table:mcp_threat_associations','has');
INSERT INTO app_edge VALUES ('area:Registry/Assessment','table:mcp_tool_hashes','has');
INSERT INTO app_edge VALUES ('area:Registry/Assessment','ui:mcp_detail_view.html','has');
INSERT INTO app_edge VALUES ('area:Registry/Assessment','ui:mcp_detail_view_ui.html','has');
INSERT INTO app_edge VALUES ('area:Registry/Assessment','ui:mcp_detail_view_ui_v2.html','has');
INSERT INTO app_edge VALUES ('area:Registry/Assessment','ui:sentinel_status.html','has');
INSERT INTO app_edge VALUES ('area:Risk/Forensics','ep:GET:/risks','has');
INSERT INTO app_edge VALUES ('area:Risk/Forensics','ep:GET:/servers/{server_id}/forensic','has');
INSERT INTO app_edge VALUES ('area:Risk/Forensics','ep:GET:/servers/{server_id}/signals','has');
INSERT INTO app_edge VALUES ('area:Risk/Forensics','ep:GET:/servers/{server_id}/threats','has');
INSERT INTO app_edge VALUES ('area:Risk/Forensics','table:github_velocity','has');
INSERT INTO app_edge VALUES ('area:Risk/Forensics','table:mcp_risk_register','has');
INSERT INTO app_edge VALUES ('area:Risk/Forensics','table:npm_typosquat_alerts','has');
INSERT INTO app_edge VALUES ('area:Risk/Forensics','table:shodan_results','has');
INSERT INTO app_edge VALUES ('area:Submissions','ep:GET:/api/submission/{id}','has');
INSERT INTO app_edge VALUES ('area:Submissions','ep:GET:/api/submissions','has');
INSERT INTO app_edge VALUES ('area:Submissions','ep:POST:/api/submissions','has');
INSERT INTO app_edge VALUES ('area:Submissions','ep:POST:/api/submit','has');
INSERT INTO app_edge VALUES ('area:Submissions','table:mcp_submissions','has');
INSERT INTO app_edge VALUES ('area:Submissions','ui:admin_submissions.html','has');
INSERT INTO app_edge VALUES ('area:Submissions','ui:mcp_submission_portal.html','has');
INSERT INTO app_edge VALUES ('ep:DELETE:/api/auth/tokens/{token_id}','table:auth_tokens','writes');
INSERT INTO app_edge VALUES ('ep:GET:/api/attestations','table:mcp_attestations','reads');
INSERT INTO app_edge VALUES ('ep:GET:/api/audit','table:mcp_decisions','reads');
INSERT INTO app_edge VALUES ('ep:GET:/api/audit','table:mcp_submissions','reads');
INSERT INTO app_edge VALUES ('ep:GET:/api/audit-log','table:audit_log','reads');
INSERT INTO app_edge VALUES ('ep:GET:/api/auth/tokens','table:auth_tokens','reads');
INSERT INTO app_edge VALUES ('ep:GET:/api/dashboard/summary','table:mcp_risk_register','reads');
INSERT INTO app_edge VALUES ('ep:GET:/api/dashboard/summary','table:mcp_server_registry','reads');
INSERT INTO app_edge VALUES ('ep:GET:/api/pathway/totals','table:mcp_discovery_candidates','reads');
INSERT INTO app_edge VALUES ('ep:GET:/api/pathway/totals','table:mcp_signal_enrichments','reads');
INSERT INTO app_edge VALUES ('ep:GET:/api/policies','table:mcp_policy_rules','reads');
INSERT INTO app_edge VALUES ('ep:GET:/api/policies','table:policy_rules','reads');
INSERT INTO app_edge VALUES ('ep:GET:/api/servers','table:mcp_server_registry','reads');
INSERT INTO app_edge VALUES ('ep:GET:/api/servers/{server_id}','table:mcp_server_registry','reads');
INSERT INTO app_edge VALUES ('ep:GET:/api/servers/{server_id}','table:mcp_signal_scores','reads');
INSERT INTO app_edge VALUES ('ep:GET:/api/submission/{id}','table:mcp_decisions','reads');
INSERT INTO app_edge VALUES ('ep:GET:/api/submission/{id}','table:mcp_submissions','reads');
INSERT INTO app_edge VALUES ('ep:GET:/api/submissions','table:mcp_submissions','reads');
INSERT INTO app_edge VALUES ('ep:GET:/api/submissions','table:mesh_events','reads');
INSERT INTO app_edge VALUES ('ep:GET:/audit/events','table:audit_log','reads');
INSERT INTO app_edge VALUES ('ep:GET:/dashboard/recent','table:mcp_server_registry','reads');
INSERT INTO app_edge VALUES ('ep:GET:/dashboard/top_risks','table:mcp_risk_register','reads');
INSERT INTO app_edge VALUES ('ep:GET:/risks','table:mcp_risk_register','reads');
INSERT INTO app_edge VALUES ('ep:GET:/servers/{server_id}/attestations','table:mcp_attestations','reads');
INSERT INTO app_edge VALUES ('ep:GET:/servers/{server_id}/forensic','table:audit_log','reads');
INSERT INTO app_edge VALUES ('ep:GET:/servers/{server_id}/forensic','table:mcp_risk_register','reads');
INSERT INTO app_edge VALUES ('ep:GET:/servers/{server_id}/override/history','table:audit_log','reads');
INSERT INTO app_edge VALUES ('ep:GET:/servers/{server_id}/signals','table:mcp_signal_scores','reads');
INSERT INTO app_edge VALUES ('ep:GET:/servers/{server_id}/threats','table:mcp_threat_associations','reads');
INSERT INTO app_edge VALUES ('ep:GET:/v1/export/csv','table:mcp_server_registry','reads');
INSERT INTO app_edge VALUES ('ep:GET:/v1/registry','table:mcp_server_registry','reads');
INSERT INTO app_edge VALUES ('ep:GET:/v1/threats','table:mcp_threat_associations','reads');
INSERT INTO app_edge VALUES ('ep:POST:/api/auth/token','table:auth_tokens','writes');
INSERT INTO app_edge VALUES ('ep:POST:/api/decision/{submission_id}','table:mcp_decisions','writes');
INSERT INTO app_edge VALUES ('ep:POST:/api/decision/{submission_id}','table:mcp_submissions','writes');
INSERT INTO app_edge VALUES ('ep:POST:/api/submissions','table:mcp_submissions','writes');
INSERT INTO app_edge VALUES ('ep:POST:/api/submissions','table:mesh_events','writes');
INSERT INTO app_edge VALUES ('ep:POST:/api/submit','table:mcp_submissions','writes');
INSERT INTO app_edge VALUES ('ep:POST:/audit','table:audit_log','writes');
INSERT INTO app_edge VALUES ('ep:POST:/override/trust','table:mcp_server_registry','writes');
INSERT INTO app_edge VALUES ('ep:POST:/override/verdict','table:mcp_server_registry','writes');
INSERT INTO app_edge VALUES ('ep:POST:/servers/{server_id}/override','table:audit_log','writes');
INSERT INTO app_edge VALUES ('ep:POST:/v1/bulk/assess','table:bulk_assess_jobs','writes');
INSERT INTO app_edge VALUES ('ep:POST:/v1/bulk/assess','table:mcp_server_registry','writes');
INSERT INTO app_edge VALUES ('ep:POST:/v1/bulk/import','table:mcp_server_registry','writes');

-- ============================ COMPLETENESS QUERIES (plain SQL) ===============
-- orphaned UIs: a uipage with NO inbound 'serves' edge (the report's headline gap)
CREATE OR REPLACE VIEW gap_orphaned_ui AS
SELECT n.area, n.name AS ui_page, n.detail AS evidence
FROM app_node n
WHERE n.kind = 'uipage'
  AND NOT EXISTS (SELECT 1 FROM app_edge e WHERE e.dst = n.id AND e.rel = 'serves')
ORDER BY n.area;

-- unwired endpoints: reach no storage
CREATE OR REPLACE VIEW gap_unwired_endpoint AS
SELECT area, name AS endpoint, file, detail AS io
FROM app_node WHERE kind = 'endpoint' AND reaches_storage = FALSE ORDER BY area;

-- schema drift: an endpoint that reads/writes a table NOT in app.sql, OR is flagged buggy
CREATE OR REPLACE VIEW gap_schema_drift AS
SELECT DISTINCT ep.area, ep.name AS endpoint, t.name AS bad_table, ep.detail AS io
FROM app_node ep
JOIN app_edge e ON e.src = ep.id AND e.rel IN ('reads','writes')
JOIN app_node t ON t.id = e.dst AND t.detail LIKE '%drift%'
WHERE ep.kind = 'endpoint'
UNION
SELECT area, '(flagged)' , name, detail FROM app_node WHERE kind='endpoint' AND is_bug = TRUE
ORDER BY 1;

-- area completeness rollup
CREATE OR REPLACE VIEW area_completeness AS
SELECT a.name AS area, a.status,
       (SELECT COUNT(*) FROM app_edge e JOIN app_node n ON n.id=e.dst
        WHERE e.src=a.id AND n.kind='endpoint') AS endpoints,
       (SELECT COUNT(*) FROM app_edge e JOIN app_node n ON n.id=e.dst
        WHERE e.src=a.id AND n.kind='uipage' AND n.served=FALSE) AS orphaned_ui,
       (SELECT COUNT(*) FROM app_edge e JOIN app_node n ON n.id=e.dst
        WHERE e.src=a.id AND n.kind='endpoint' AND n.is_bug=TRUE) AS buggy_endpoints
FROM app_node a WHERE a.kind='area' ORDER BY a.status DESC, area;

-- ============================ DuckPGQ (optional, elegant layer) ==============
-- The SAME questions as property-graph MATCH. Needs the extension:
--   INSTALL duckpgq FROM community; LOAD duckpgq;
--   CREATE PROPERTY GRAPH app
--     VERTEX TABLES (app_node)
--     EDGE TABLES (app_edge
--       SOURCE KEY (src) REFERENCES app_node (id)
--       DESTINATION KEY (dst) REFERENCES app_node (id));
--   -- e.g. a UI that calls an endpoint that touches a drift table (multi-hop):
--   -- FROM GRAPH_TABLE (app
--   --   MATCH (u:app_node WHERE u.kind='uipage')-[:has]-(:app_node)
--   --         -[:reads|writes]->(t:app_node WHERE t.detail LIKE '%drift%')
--   --   COLUMNS (u.name, t.name));
