#!/usr/bin/env bash
# Make sure this host HAS a cron daemon, and say so either way.
#
# WHY THIS EXISTS
#   tools/bus_catalog_guard.sh is registered in the host crontab three ways --
#   @reboot, hourly, and 05:17 -- specifically so a missed slot heals itself
#   (#4032 Phase H). On 2026-08-27 none of the three had ever run. The crontab
#   was correct. There was no cron daemon.
#
#     $ pgrep -a cron          -> (nothing)
#     $ ls /usr/sbin/cron      -> /usr/sbin/cron          # installed
#     $ ls /etc/init.d/cron    -> /etc/init.d/cron        # registered
#     $ pgrep -a supervisord   -> two, from the substrate entrypoint
#
#   The container's process supervisor is supervisord, started by
#   /__substrate/entrypoint.sh. Nothing in that path starts cron. So every
#   crontab line on the box was inert, including the @reboot line whose entire
#   purpose was to survive the box being off at 05:17.
#
#   Three triggers on one dead scheduler is not redundancy. It is one scheduler
#   wearing three hats -- and it looked exactly like redundancy from the
#   crontab, which is why nobody checked the daemon.
#
# WHAT THIS CANNOT DO, HONESTLY
#   It cannot claim a boot hook. /etc/zo/supervisord-user.conf is regenerated by
#   the substrate from an environment variable at boot, and the entrypoint reads
#   nothing from /home/workspace. So after a COLD BOOT this script has not run
#   yet and cron is still dead until something runs it.
#
#   That gap is covered from OFF the host: .github/workflows/bus-catalog-freshness.yml
#   runs on GitHub's scheduler and turns red a full week before the snapshot
#   ages past referent-verify's budget. That alarm cannot be silenced by the
#   thing it is watching, which is the property the host half can never have.
#
# Usage:  ops/host/ensure_cron_running.sh [--quiet]
set -uo pipefail

HEARTBEAT="${ZO_CRON_HEARTBEAT:-/home/workspace/logs/cron_daemon_heartbeat.json}"
QUIET=0
[ "${1:-}" = "--quiet" ] && QUIET=1

log() { [ "$QUIET" = "1" ] || echo "[cron-guard] $(date -u +%Y-%m-%dT%H:%M:%SZ) $*"; }

WAS_RUNNING=0
ACTION="none"
if pgrep -x cron >/dev/null 2>&1 || pgrep -x crond >/dev/null 2>&1; then
    WAS_RUNNING=1
    log "cron daemon is running"
else
    log "NO CRON DAEMON -- every crontab entry on this host is inert"
    if [ -x /etc/init.d/cron ]; then
        /etc/init.d/cron start >/dev/null 2>&1 && ACTION="started via /etc/init.d/cron"
    fi
    if [ "$ACTION" = "none" ] && command -v service >/dev/null 2>&1; then
        service cron start >/dev/null 2>&1 && ACTION="started via service"
    fi
    if [ "$ACTION" = "none" ] && command -v cron >/dev/null 2>&1; then
        cron && ACTION="started via cron(8) directly"
    fi
    sleep 1
    if pgrep -x cron >/dev/null 2>&1 || pgrep -x crond >/dev/null 2>&1; then
        log "cron daemon started ($ACTION)"
    else
        ACTION="FAILED to start"
        log "ERROR: could not start a cron daemon. Scheduled host work is DEAD."
    fi
fi

# Heartbeat on EVERY path, including the healthy one. A heartbeat that only
# appears when something was wrong cannot distinguish "healthy" from "not run".
mkdir -p "$(dirname "$HEARTBEAT")" 2>/dev/null
python3 - "$HEARTBEAT" "$WAS_RUNNING" "$ACTION" <<'PY'
import json, subprocess, sys
from datetime import datetime, timezone
path, was_running, action = sys.argv[1:4]
try:
    n = len([l for l in subprocess.run(["crontab", "-l"], capture_output=True,
                                       text=True).stdout.splitlines()
             if l.strip() and not l.strip().startswith("#")])
except Exception:
    n = -1
json.dump({
    "checked_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    "daemon_was_running": was_running == "1",
    "action": action,
    "crontab_entries": n,
}, open(path, "w"), indent=2)
PY
log "heartbeat -> $HEARTBEAT"

# Exit 1 when we had to intervene, so a run from cron itself is silent and a run
# that found the scheduler dead is loud wherever it is invoked from.
[ "$WAS_RUNNING" = "1" ] && exit 0
exit 1
