#!/usr/bin/env python3
"""build_app_graph.py -- turn the capability map (capmap.json) into an APP-MODEL
GRAPH: node/edge tables + completeness queries. This is the "held / should"
layer of the runtime knowledge graph -- the live-queryable successor to the
static feature_completeness.html report.

It emits ONE self-contained SQL file (schema/app_graph.sql) that:
  * creates app_node / app_edge,
  * seeds them from capmap.json,
  * defines completeness VIEWS in PLAIN SQL (work on today's DuckDB, no extension),
  * and adds the DuckPGQ property-graph + MATCH equivalents as the elegant layer
    (optional -- needs `INSTALL duckpgq FROM community`).

The value (queryable app model + gap queries) does NOT require DuckPGQ; the views
are 1-2 hop joins. DuckPGQ just makes multi-hop graph queries ergonomic.

    python tools/build_app_graph.py [capmap.json] [out.sql]
    duckdb :memory: < schema/app_graph.sql       # run the gap queries
"""
import json, sys, os, re

CAP = sys.argv[1] if len(sys.argv) > 1 else "C:/tmp/capmap.json"
OUT = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "schema", "app_graph.sql")

# canonical app tables -- read straight from schema/app.sql so there's ONE source
# of truth (adopting a table = editing app.sql only; no second list to maintain).
# Anything an endpoint references OUTSIDE this set is schema drift.
def _canon_tables():
    p = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "schema", "app.sql")
    try:
        return set(re.findall(r'CREATE TABLE IF NOT EXISTS (\w+)', open(p, encoding="utf-8").read()))
    except Exception:
        return set()

CANON = _canon_tables()
BUGWORDS = ("wrong table", "not in schema", "absent from schema", "mismatch",
            "WRONG", "effectively false")
TABLE_RE = re.compile(r"[a-z_][a-z0-9_]{3,}")

def q(s):  # SQL string literal
    return "'" + str(s).replace("'", "''") + "'"

def b(x):  # SQL bool
    return "TRUE" if x else "FALSE"

def main():
    with open(CAP, encoding="utf-8") as f:
        data = json.load(f)

    nodes = {}   # id -> dict
    edges = []   # (src, dst, rel)

    def node(nid, **kw):
        nodes.setdefault(nid, {"id": nid, "kind": "", "name": "", "area": "",
                               "file": "", "status": "", "served": None,
                               "reaches_storage": None, "is_bug": None, "detail": ""})
        nodes[nid].update({k: v for k, v in kw.items() if v is not None})

    for a in data.get("areas", []):
        an = f"area:{a['name']}"
        node(an, kind="area", name=a["name"], area=a["name"], status=a.get("status", ""),
             detail="; ".join(a.get("gaps", []))[:500])
        for t in a.get("tables", []):
            tn = f"table:{t}"
            node(tn, kind="table", name=t, area=a["name"],
                 detail=("" if t in CANON else "NOT in app.sql (drift)"))
            edges.append((an, tn, "has"))
        for e in a.get("endpoints", []):
            io = e.get("io", "")
            eid = f"ep:{e['method']}:{e['path']}"
            is_bug = (not e.get("reaches_storage", False)) or any(
                w.lower() in io.lower() for w in BUGWORDS)
            node(eid, kind="endpoint", name=f"{e['method']} {e['path']}", area=a["name"],
                 file=e.get("file", ""), reaches_storage=e.get("reaches_storage", False),
                 is_bug=is_bug, detail=io[:300])
            edges.append((an, eid, "has"))
            # endpoint -> table edges parsed from the io text (canonical + drift tables)
            verb = "writes" if re.search(r"write|update|insert", io, re.I) else "reads"
            for tok in set(TABLE_RE.findall(io)):
                if tok in CANON or tok in {"mesh_events", "policy_rules"}:
                    tn = f"table:{tok}"
                    node(tn, kind="table", name=tok, area=a["name"],
                         detail=("" if tok in CANON else "NOT in app.sql (drift)"))
                    edges.append((eid, tn, verb))
        for u in a.get("ui", []):
            un = f"ui:{u['file']}"
            node(un, kind="uipage", name=u["file"], area=a["name"],
                 served=u.get("served", False), detail=u.get("evidence", "")[:300])
            edges.append((an, un, "has"))
            if u.get("served"):
                edges.append((an, un, "serves"))

    # de-dup edges
    edges = sorted(set(edges))

    lines = []
    P = lines.append
    P("-- app_graph.sql -- GENERATED by tools/build_app_graph.py from capmap.json")
    P("-- The app-model knowledge graph: node/edge tables + completeness queries.")
    P("-- Re-generate after refreshing capmap.json. Plain-SQL views need no extension.\n")
    P("DROP TABLE IF EXISTS app_edge; DROP TABLE IF EXISTS app_node;")
    P("""CREATE TABLE app_node (
  id VARCHAR PRIMARY KEY, kind VARCHAR, name VARCHAR, area VARCHAR, file VARCHAR,
  status VARCHAR, served BOOLEAN, reaches_storage BOOLEAN, is_bug BOOLEAN, detail VARCHAR);""")
    P("CREATE TABLE app_edge (src VARCHAR, dst VARCHAR, rel VARCHAR);\n")

    for n in nodes.values():
        P(f"INSERT INTO app_node VALUES ({q(n['id'])},{q(n['kind'])},{q(n['name'])},"
          f"{q(n['area'])},{q(n['file'])},{q(n['status'])},"
          f"{b(n['served']) if n['served'] is not None else 'NULL'},"
          f"{b(n['reaches_storage']) if n['reaches_storage'] is not None else 'NULL'},"
          f"{b(n['is_bug']) if n['is_bug'] is not None else 'NULL'},{q(n['detail'])});")
    P("")
    for s, d, r in edges:
        P(f"INSERT INTO app_edge VALUES ({q(s)},{q(d)},{q(r)});")

    P("""
-- ============================ COMPLETENESS QUERIES (plain SQL) ===============
-- orphaned UIs: a uipage with NO inbound 'serves' edge (the report's headline gap)
CREATE OR REPLACE VIEW gap_orphaned_ui AS
SELECT n.area, n.name AS ui_page, n.detail AS evidence
FROM app_node n
WHERE n.kind = 'uipage'
  AND NOT EXISTS (SELECT 1 FROM app_edge e WHERE e.dst = n.id AND e.rel = 'serves')
ORDER BY n.area;

-- unwired endpoints: reach no storage
CREATE OR REPLACE VIEW gap_unwired_endpoint AS
SELECT area, name AS endpoint, file, detail AS io
FROM app_node WHERE kind = 'endpoint' AND reaches_storage = FALSE ORDER BY area;

-- schema drift: an endpoint that reads/writes a table NOT in app.sql, OR is flagged buggy
CREATE OR REPLACE VIEW gap_schema_drift AS
SELECT DISTINCT ep.area, ep.name AS endpoint, t.name AS bad_table, ep.detail AS io
FROM app_node ep
JOIN app_edge e ON e.src = ep.id AND e.rel IN ('reads','writes')
JOIN app_node t ON t.id = e.dst AND t.detail LIKE '%drift%'
WHERE ep.kind = 'endpoint'
UNION
SELECT area, '(flagged)' , name, detail FROM app_node WHERE kind='endpoint' AND is_bug = TRUE
ORDER BY 1;

-- area completeness rollup
CREATE OR REPLACE VIEW area_completeness AS
SELECT a.name AS area, a.status,
       (SELECT COUNT(*) FROM app_edge e JOIN app_node n ON n.id=e.dst
        WHERE e.src=a.id AND n.kind='endpoint') AS endpoints,
       (SELECT COUNT(*) FROM app_edge e JOIN app_node n ON n.id=e.dst
        WHERE e.src=a.id AND n.kind='uipage' AND n.served=FALSE) AS orphaned_ui,
       (SELECT COUNT(*) FROM app_edge e JOIN app_node n ON n.id=e.dst
        WHERE e.src=a.id AND n.kind='endpoint' AND n.is_bug=TRUE) AS buggy_endpoints
FROM app_node a WHERE a.kind='area' ORDER BY a.status DESC, area;

-- ============================ DuckPGQ (optional, elegant layer) ==============
-- The SAME questions as property-graph MATCH. Needs the extension:
--   INSTALL duckpgq FROM community; LOAD duckpgq;
--   CREATE PROPERTY GRAPH app
--     VERTEX TABLES (app_node)
--     EDGE TABLES (app_edge
--       SOURCE KEY (src) REFERENCES app_node (id)
--       DESTINATION KEY (dst) REFERENCES app_node (id));
--   -- e.g. a UI that calls an endpoint that touches a drift table (multi-hop):
--   -- FROM GRAPH_TABLE (app
--   --   MATCH (u:app_node WHERE u.kind='uipage')-[:has]-(:app_node)
--   --         -[:reads|writes]->(t:app_node WHERE t.detail LIKE '%drift%')
--   --   COLUMNS (u.name, t.name));
""")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    kinds = {}
    for n in nodes.values():
        kinds[n["kind"]] = kinds.get(n["kind"], 0) + 1
    print(f"wrote {OUT}")
    print(f"  nodes: {len(nodes)} {kinds}")
    print(f"  edges: {len(edges)}  rels: {sorted(set(r for _,_,r in edges))}")

if __name__ == "__main__":
    main()
