#!/usr/bin/env bash
# Host-side refresher for schema/bus_catalog.json.
#
# WHY THIS FILE IS IN THE REPO
#   The 2026-04 E2E runner died because its activation -- wire_test_hooks.py
#   patching an untracked zo_sentinel_builder.py -- lived outside version
#   control. Nothing recorded that it had stopped, and no commit could record
#   why, because nothing that happened was a commit. This script is the
#   activation for the referent gate's host half, so it is tracked, reviewable,
#   and diffable. The crontab line calls this file and holds no logic of its own.
#
# WHAT IT DOES
#   Reads the live bus catalog (paginated) in a CLEAN worktree of origin/main --
#   never the build workspace, whose untracked files are the B2 failure mode --
#   and pushes a refresh branch when EITHER:
#     - the catalog content actually changed (tables/columns added or removed), or
#     - the committed snapshot is over HEARTBEAT_DAYS old.
#
#   Refreshing on content-change alone would let captured_at drift past the
#   checker's staleness budget while the schema happened to be stable, turning a
#   healthy system red. Refreshing every night would open a no-op PR every night
#   and train everyone to ignore it. So: on change, or on heartbeat.
#
# Usage:  tools/bus_catalog_refresh.sh [--dry-run]
set -euo pipefail

REPO="${ZO_REPO:-/home/workspace/zo_sentinel}"
WORK="${ZO_CATALOG_WORKTREE:-/home/workspace/.catalog_refresh_wt}"
HEARTBEAT_DAYS="${HEARTBEAT_DAYS:-7}"
BRANCH="auto/catalog/bus-catalog-refresh"
# Overridable so the refresher can be exercised end-to-end before it is on main.
BASE_REF="${ZO_CATALOG_BASE_REF:-origin/main}"
SNAP="schema/bus_catalog.json"
DRY=0
[ "${1:-}" = "--dry-run" ] && DRY=1

log() { echo "[catalog-refresh] $*"; }

cd "$REPO"
git fetch -q origin

# Clean worktree of origin/main. Rebuilt each run so nothing accumulates in it.
git worktree remove --force "$WORK" 2>/dev/null || true
rm -rf "$WORK"
git worktree add -q --detach "$WORK" "$BASE_REF"
trap 'cd "$REPO" && git worktree remove --force "$WORK" 2>/dev/null || true' EXIT

cd "$WORK"

# Distinguish "the tool is not on main yet" from "the bus is down". The first
# cut of this script reported a MISSING SCRIPT as "bus unreachable" -- the same
# conflation of two different unknowns that this whole gate exists to stop.
if [ ! -f tools/bus_catalog_snapshot.py ]; then
    log "ERROR: tools/bus_catalog_snapshot.py absent from $BASE_REF."
    log "       The refresher cannot run until PR #4036 merges. This is a"
    log "       missing tool, NOT an unreachable bus."
    exit 3
fi

if ! python3 tools/bus_catalog_snapshot.py --emit "$SNAP"; then
    # Non-zero here means the bus was unreachable. Leave the committed snapshot
    # alone: an old-but-true catalog is recoverable, and the checker will call
    # it UNKNOWN once it ages out. Overwriting it with a partial or empty read
    # would be worse -- that manufactures false MISSING verdicts.
    log "bus unreachable; committed snapshot left untouched"
    exit 2
fi

if git diff --quiet -- "$SNAP"; then
    log "catalog byte-identical; nothing to do"
    exit 0
fi

# Distinguish a real schema change from a captured_at-only bump.
CONTENT_CHANGED=$(python3 - <<'PY'
import json, subprocess, sys
new = json.load(open("schema/bus_catalog.json"))
old = json.loads(subprocess.run(
    ["git", "show", "HEAD:schema/bus_catalog.json"],
    capture_output=True, text=True).stdout or "{}")
print("1" if new.get("tables") != old.get("tables") else "0")
PY
)

AGE_DAYS=$(python3 - <<'PY'
import json, subprocess
from datetime import datetime, timezone
try:
    old = json.loads(subprocess.run(
        ["git", "show", "HEAD:schema/bus_catalog.json"],
        capture_output=True, text=True).stdout)
    ts = datetime.fromisoformat(old["captured_at"])
    if ts.tzinfo is None:
        ts = ts.replace(tzinfo=timezone.utc)
    print(int((datetime.now(timezone.utc) - ts).total_seconds() // 86400))
except Exception:
    print(999)
PY
)

log "content_changed=$CONTENT_CHANGED committed_age=${AGE_DAYS}d heartbeat=${HEARTBEAT_DAYS}d"

if [ "$CONTENT_CHANGED" = "0" ] && [ "$AGE_DAYS" -lt "$HEARTBEAT_DAYS" ]; then
    log "timestamp-only change inside heartbeat window; not pushing"
    exit 0
fi

if [ "$DRY" = "1" ]; then
    log "DRY RUN -- would push $BRANCH"
    git --no-pager diff --stat -- "$SNAP"
    exit 0
fi

REASON="heartbeat refresh (${AGE_DAYS}d old)"
[ "$CONTENT_CHANGED" = "1" ] && REASON="bus schema changed"

git checkout -q -b "$BRANCH"
git add "$SNAP"
git -c user.name="substrate-bot" -c user.email="substrate-bot@users.noreply.github.com" \
    commit -q -m "chore(catalog): refresh bus_catalog.json -- ${REASON}

Regenerated by tools/bus_catalog_refresh.sh from the live write-service
catalog, paginated and reconciled against COUNT(*).

Keeping this current is what lets tools/referent_verify.py render a verdict at
all: once the snapshot passes its staleness budget the checker reports UNKNOWN
and stops claiming the tables are fine. Refs #4032."
git push -q -f origin "$BRANCH"
log "pushed $BRANCH ($REASON)"
