#!/usr/bin/env python3
"""ingest_observed_edges.py -- the "observed / is" half of the app-model graph.

Reads the ndjson that app_shell.py emits (one line per proxied request: which UI
page called which endpoint on which service) and turns it into SQL that adds
`observed_calls` edges to the app graph. Run it after build_app_graph.py, then:

    duckdb mygraph.db < schema/app_graph.sql            # held "should"
    python tools/ingest_observed_edges.py                # emits app_graph_observed.sql
    duckdb mygraph.db < schema/app_graph_observed.sql    # observed "is"

The payoff queries (defined here):
  * gap_orphaned_ui_true     -- static-orphaned UIs with NO live calls (REAL gaps)
  * gap_orphaned_ui_falsepos -- "orphaned" by static analysis but ACTUALLY active
                                (the exact false-positive we hit; now self-correcting)

    python tools/ingest_observed_edges.py [observed.ndjson] [out.sql]
"""
import json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "app_observed_edges.ndjson")
OUT = sys.argv[2] if len(sys.argv) > 2 else os.path.join(ROOT, "schema", "app_graph_observed.sql")

ID_SEG = re.compile(r"/(?:[0-9a-f]{8,}|\d+)(?=/|$)", re.I)  # collapse id-ish path segments

def q(s):
    return "'" + str(s).replace("'", "''") + "'"

def norm(path):
    return ID_SEG.sub("/{id}", path)

def main():
    edges, endpoints = set(), {}
    n_lines = 0
    if os.path.isfile(SRC):
        with open(SRC, encoding="utf-8", errors="replace") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    r = json.loads(line)
                except Exception:
                    continue
                n_lines += 1
                path = norm(r.get("path", ""))
                ep = f"ep:{r.get('method','')}:{path}"
                endpoints[ep] = {"name": f"{r.get('method','')} {path}",
                                 "port": r.get("port"), "prefix": r.get("prefix", "")}
                ui = r.get("ui", "")
                if ui and ui.endswith(".html"):
                    edges.add((f"ui:{ui}", ep))

    lines = ["-- app_graph_observed.sql -- GENERATED by tools/ingest_observed_edges.py",
             f"-- from {os.path.basename(SRC)} ({n_lines} request lines, "
             f"{len(endpoints)} endpoints, {len(edges)} observed UI->endpoint edges)\n"]
    for ep, m in sorted(endpoints.items()):
        # add observed endpoints not already present (held graph may use templated paths)
        lines.append(
            f"INSERT INTO app_node (id,kind,name,detail) VALUES "
            f"({q(ep)},'endpoint',{q(m['name'])},{q('observed via '+m['prefix'])}) "
            f"ON CONFLICT (id) DO NOTHING;")
    for src, dst in sorted(edges):
        lines.append(f"INSERT INTO app_edge VALUES ({q(src)},{q(dst)},'observed_calls');")

    lines.append("""
-- which UI pages are ACTUALLY active (made >=1 live call through the shell)
CREATE OR REPLACE VIEW ui_observed_active AS
SELECT DISTINCT src AS ui_id FROM app_edge WHERE rel = 'observed_calls';

-- REAL orphans: static-orphaned AND never observed calling anything
CREATE OR REPLACE VIEW gap_orphaned_ui_true AS
SELECT area, ui_page FROM gap_orphaned_ui
WHERE ('ui:' || ui_page) NOT IN (SELECT ui_id FROM ui_observed_active);

-- FALSE POSITIVES: "orphaned" by static analysis but observed making live calls
-- (this is the exact mistake we hit -- the graph now self-corrects it)
CREATE OR REPLACE VIEW gap_orphaned_ui_falsepos AS
SELECT area, ui_page FROM gap_orphaned_ui
WHERE ('ui:' || ui_page) IN (SELECT ui_id FROM ui_observed_active);
""")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT}  ({n_lines} lines -> {len(endpoints)} endpoints, {len(edges)} observed edges)")
    if n_lines == 0:
        print(f"  (no observed data yet -- run the shell with OBSERVE=1 and exercise the UI; "
              f"expected at {SRC})")

if __name__ == "__main__":
    main()
