"""
breaker_actions/breaker_action_investigate_tenant_org_model.py

This module implements the *investigate* breaker action for the
`tenant_org_model.py` source file.  The file has been placed in quarantine
and is reported as `missing_on_disk`, which is a severe failure condition.
The purpose of this action is **not** to attempt a rebuild, but to emit a
structured request that a higher‑level workflow can consume (e.g. a human
investigation ticket, an alert, or a CI‑pipeline pause).

The module provides a single public entry point – ``run`` – which returns a
dictionary describing the investigation request.  The dictionary format is
consistent with other breaker‑action modules in the repository and can be
easily serialized to JSON or logged.

Typical usage:

    from breaker_actions.breaker_action_investigate_tenant_org_model import run

    result = run()
    # result is a dict that can be inspected or forwarded to the orchestration layer
"""

from __future__ import annotations

from datetime import datetime
from typing import Dict


def _build_payload() -> Dict[str, str]:
    """
    Construct the payload that describes the investigation request.

    Returns
    -------
    dict
        A mapping with the following keys:
        - ``action``: The breaker action name (always ``investigate``).
        - ``target``: The relative path of the problematic file.
        - ``status``: The quarantine status of the file.
        - ``reason``: The specific reason why investigation is required.
        - ``timestamp``: ISO‑8601 UTC timestamp when the payload was generated.
        - ``message``: Human‑readable description of the situation.
    """
    return {
        "action": "investigate",
        "target": "tenant_org_model.py",
        "status": "quarantined",
        "reason": "missing_on_disk",
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "message": (
            "The file `tenant_org_model.py` is quarantined and missing on disk. "
            "An investigation is required before any further build attempts."
        ),
    }


def run() -> Dict[str, str]:
    """
    Execute the *investigate* breaker action for ``tenant_org_model.py``.

    This function does **not** attempt to rebuild the file.  Instead it
    returns a structured description that downstream tooling can interpret
    as a request to halt the pipeline and open an investigation ticket.

    Returns
    -------
    dict
        The investigation payload generated by :func:`_build_payload`.
    """
    return _build_payload()